src/client/clientauthhandler.cpp
The QDataStream used to talk to the core is set to version Qt_4_2 everywhere except in the ClientAuthHandler. It works without problems at the moment because the ClientAuthHandler only transmits a quint32, but for consistency it makes sense to set the version here too.
=> Set the version of the QDataStream in ClientAuthHandler

CMakeLists.txt, cmake/FindQCA2-QT5.cmake, src/common/CMakeLists.txt, src/core/CMakeLists.txt
The maintainer for QCA insists on adding a suffix to the QCA
libname, forcing us to make a few changes to support it.
=> Add support for compiling with QCA on Qt5

src/client/clientsettings.cpp, src/client/clientsettings.h, src/client/coreconnection.cpp, src/client/coreconnection.h, src/qtui/settingspages/coreconnectionsettingspage.cpp, src/qtui/settingspages/coreconnectionsettingspage.ui
A new network detection mode is added to use QNetworkConfigurationManager, available in Qt4.7+ including Qt5. This becomes the default mode when KDE4 integration is not available.
CMakeLists.txt just assumes the availability of QNetworkConfigurationManager based on Qt version. I haven't figured out how to actually check it, and I don't know if it will be necessary.
I've tested that it compiles with -DUSE_QT4 or -DUSE_QT5.
By the way, Networking is not available in KF5 Solid, and [porting notes](https://community.kde.org/Frameworks/Porting_Notes#Solid_Networking) point to QNetworkConfigurationManager.
=> Add QNetworkConfigurationManager-based connection detection

src/core/corenetwork.cpp
Previously, disconnectFromIrc() would assume that if the socket was
in any state other than ConnectedState that it was disconnected and
send the socketDisconnected() signal.  However, if the socket was
in a different state, such as ConnectingState, this caused the
corenetwork state and the socket state to become desynchronized.
This patch causes disconnectFromIrc() to close the socket and
start the socketCloseTimer in the event that the socket is in a
state other than UnconnectedState or ConnectedState.
=> Fix potential state desync in disconnectFromIrc()

src/qtui/settingspages/networkssettingspage.cpp
When adding a new server, setting the initial focus to the host input widget speeds up the process by a lot.
=> Set initial focus to host input widget.

CMakeLists.txt
some additional cmake magic, make sense in a build chroot where the upstream repo is not available - i don't want to build git snapshots local - but i would like to have the information, what is build in the about box
=> set GIT_HEAD and GIT_DESCRIBE from environment

src/common/main.cpp, src/core/coreauthhandler.cpp
Encrypting a loopback connection is a pointless waste of computing
power.  This patch will allow people to use loopback connections
from things like quassel-webserver without encryption while still
requiring encryption for remote connections.
=> Don't require SSL for loopback connections with --require-ssl

src/client/coreconnection.h, src/common/internalpeer.h, src/common/peer.h, src/common/protocol.h, src/common/remotepeer.h, src/qtui/settingspages/networkssettingspage.cpp, src/qtui/settingspages/servereditdlg.ui
Cores before 0.10 will default to SSLv3 if the user doesn't make a
selection.  If a >=0.10 client is used with a <0.10 core to connect
to a server that has SSLv3 disabled, it is impossible to connect
to that server without upgrading the core or using an old client
to change the SSL protocol settings.
This also changes the SSLv2 and SSLv3 options to indicate their
insecurity and therefore discourage their use.
Cores from 0.10 and up use SSL autonegotiation and to not need the
protocol setting.
This partially reverts commit
e53fc69a91553b57932ba599b39999d550114588.
=> Add back the SSL protocol selection dialog box for old cores.

src/core/corebasichandler.cpp, src/core/corebasichandler.h, src/core/corenetwork.cpp, src/core/corenetwork.h, src/core/coreuserinputhandler.cpp, src/core/coreuserinputhandler.h, src/core/ctcpparser.cpp
This introduces a new message splitting algorithm based on
QTextBoundaryFinder.  It works by first starting with the entire
message to be sent, encoding it, and checking to see if it is over
the maximum message length.  If it is, it uses QTBF to find the
word boundary most immediately preceding the maximum length.  If no
suitable boundary can be found, it falls back to searching for
grapheme boundaries.  It repeats this process until the entire
message has been sent.
Unlike what it replaces, the new splitting code is not recursive
and cannot cause stack overflows.  Additionally, if it is unable
to split a string, it will give up gracefully and not crash the
core or cause a thread to run away.
This patch fixes two bugs.  The first is garbage characters caused
by accidentally splitting the …
=> Improve the message-splitting algorithm for PRIVMSG and CTCP

src/core/SQL/PostgreSQL/17/setup_000_quasseluser.sql, src/core/SQL/SQLite/18/setup_000_quasseluser.sql
I'm not sure whether this slipped out in a merge or whether I
forgot to add it in the first place, but it should have been part
of commit 5924533c6d0f9777d38c01ed7e1510a55db2b876.  This
completely broke setting up a new Quassel instance from scratch
with 0.12-rc1, but upgrades from previous versions are unaffected.
=> Update the schema creation DDL for the new password hashing

src/core/postgresqlstorage.cpp
With Qt5, the PostgreSQL driver will transparently convert times
to the database's timezone before inserting.  Because the default
is 'localtime', this causes the local time to be stored in the DB
instead of the UTC time.  This in turn causes the time displayed
in the client to be wrong by the same offset as that timezone's
offset.  To fix the issue, just make sure the PostgreSQL is in the
'UTC' timezone, so the passed UTC time will not be converted.
=> Set the PostgreSQL session timezone to 'UTC'

src/core/abstractsqlstorage.cpp, src/core/abstractsqlstorage.h
Previously, the initDbSession() function would only be run on the
initial connect.  Since the initDbSession() code in PostgreSQL is
used to fix the CVE-2013-4422 SQL Injection bug, this means that
Quassel was still vulnerable to that CVE if the PostgreSQL server
is restarted or the connection is lost at any point while Quassel
is running.
This bug also causes the Qt5 psql timezone fix to stop working
after a reconnect.
The fix is to disable Qt's automatic reconnecting, check the
connection status ourselves, and reconnect if necessary, executing
the initDbSession() function afterward.
=> Execute initDbSession() on DB reconnects

src/core/postgresqlstorage.cpp
At least on Qt5, the QSqlQuery.lastQuery() function, when used with
prepared queries, returns the EXECUTE statement and not the actual
query.  Qt then attempts to PREPARE this statement, which causes
a syntax error, aborting the transaction and dropping the message that
was to be inserted.  A better idea would be to execute the named
prepared query directly, which avoids the problem.
=> Fix SQL errors caused by sender insertion from multiple threads

src/common/main.cpp, src/core/sslserver.cpp, src/core/sslserver.h
Add option to core to specify SSL certificate and
SSL key path, --ssl-cert and --ssl-key respectively.
If not set, the 'legacy' path configdir/quasselCert.pem
will be used for the cert and the key.
=> Add core options to specify path to ssl certs.

CMakeLists.txt, src/qtui/CMakeLists.txt
It seems that as of 2273a95b, Webkit support is always compiled in as long as it's available, regardless of the value of WITH_WEBKIT.
I've modified the Qt 5 portion of the Webkit detection to mirror the Qt 4 logic, so HAVE_WEBKIT should always be set correctly.
=> Respect WITH_WEBKIT when defining HAVE_WEBKIT

src/client/clientauthhandler.cpp, src/client/clientauthhandler.h
Previously, MD5 was used.  Like the core password hashing update,
this implements a versioning system so that the digest will be
automagically upgraded without bugging the user.  If for some
reason the user downgrades again, the client will still work but
the user will be asked to validate the certificate again.
SHA2-256 is more common for storing certificate digests, but in
this case, SHA2-512 was used.  This is because Qt4 does not
implement any hash higher than SHA1 and a SHA2-512 implementation
is already bundled for use with the core password hashing.
=> Use SHA2-512 to store the core certificate digest in the client

src/client/coreconnection.cpp
Previously _wantReconnect was set to false by default (unless the
client was actually disconnected).  If the disconnect() signal was
fired without any other signals (socketError(), for example), this
would cause the client to not reconnect.  This seems to be
happening rather often with Qt5 client builds because a vast
majority of the time when I restart my core (or the entire core
server), the Qt5 clients do not reconnect.  This patch keeps
_wantReconnect set to true whenever the client is connected so that
problem will not occur anymore.  Disconnecting manually will set
it back to false so that the client won't try to reconnect after
a manual disconnect.
=> Keep _wantReconnect set to true by default instead of false

src/core/corenetwork.cpp
This makes sure that socketDisconnected() is always called when
Quassel disconnects even if it isn't fully connected yet.
Otherwise, reconnect occasionally fails to work properly.
=> Call socketDisconnected() from socketStateChanged()

src/qtui/dockmanagernotificationbackend.cpp, src/qtui/dockmanagernotificationbackend.h
This gets rid of the stray debug message introduced by 0bf9227 and adds
some visual feedback on the settingspage instead.
=> Disable checkbox if no DockManager is present

src/core/coreircchannel.cpp, src/core/corenetwork.h
The refactoring from 3146ad0 (and e0781ee) was not a true refactoring as
it changed behaviour: CoreIrcChannels (as opposed to CoreNetworks) are
ephemeral, which meant disconnecting or parting lost the channel key.
Keys are still kept by the channel's cipher, but synced from/to its network when
the constructor/destructor is called.
Fixes #1248
=> Store the channel keys in CoreNetwork again

src/uisupport/multilineedit.cpp
By default QTextHtmlImporter::appendNodeText replaces white-space
characters with a single space and leading white-space is removed. When
white-space is set to pre-wrap in the style of the node, it is preserved
instead.
Given that contents are in a span element, setting white-space to
pre-wrap on span makes the setHtml call do the expected thing.
=> Preserve white-space in the input history.

src/core/coreuserinputhandler.cpp
Without the patch, the following backtrace is created:
```
2015-10-21 02:54:28 Debug: Quassel IRC:  "0.13-pre"   "b49c64970b6237fc95f8ca88c8bb6bcf04c251d7"  
2015-10-21 02:54:28 Debug: #  0 quasselcore          0x0000000000568617 Quassel::logBacktrace(QString const&)  
2015-10-21 02:54:28 Debug: #  1 quasselcore          0x000000000054908c Quassel::handleSignal(int)  
2015-10-21 02:54:28 Debug: #  2 libc.so.6            0x00007fb90e1e5670 0x0000000000000000  
2015-10-21 02:54:28 Debug: #  3 quasselcore          0x00000000004bf5c0 QHash<IrcUser*, QString>::size() const  
2015-10-21 02:54:28 Debug: #  4 quasselcore          0x00000000004c1849 QHash<IrcUser*, QString>::keys() const  
2015-10-21 02:54:28 Debug: #  5 quasselcore          0x00000000004c1901 IrcChannel::ircUsers() const …
```
=> Fixes a crash of the core when executing "/op *" in a query.

src/core/core.cpp, src/core/core.h
Maybe it is not a common use case to include a user addition in a script, but in such case we need this.
=> quasselcore: fixed return values for --add-user and --change-userpass

src/qtui/mainpage.cpp, src/qtui/mainpage.h, src/qtui/mainwin.cpp, src/qtui/nicklistwidget.cpp, src/qtui/nicklistwidget.h
Instead of overriding the paint function simply use a layout and a QLabel in MainPage, this also enables us to add a button to open the connect to core dialog.
This commit also hides the Nick list in a disconnected state, to make sure the Quassel logo is centred and to keep it in line with the All Chats view.
=> Improve MainPage

CMakeLists.txt
CMAKE_POSITION_INDEPENDENT_CODE will always append fPIE flag as last compiler flag when calling try_compile which makes check_cxx_source_compiles fails. Move the SSL check before set CMAKE_POSITION_INDEPENDENT_CODE and append Qt5Core_EXECUTABLE_COMPILE_FLAGS to CMAKE_CXX_FLAGS solve the problem.
=> Fix SSL detection

src/core/corenetwork.cpp, src/core/corenetwork.h
This creates an entry for the port as soon as the socket is opened,
without duplicates. This allows an identd service to respond correctly
if a request is received before the SSL handshake has finished and been
processed on our side.
Since socketOpen is not used in the project, it is removed here.
Since the only usage of socketInitialized(...) is with oidentd, its
semantic meaning is slightly changed to occur earlier, like socketOpen,
but only once, like the former socketInitialized(...).
=> Fix ident race condition

src/core/SQL/PostgreSQL/17/migrate_write_quasseluser.sql, src/core/SQL/SQLite/18/migrate_read_quasseluser.sql, src/core/abstractsqlstorage.h, src/core/postgresqlstorage.cpp, src/core/sqlitestorage.cpp
Previously, hashversion was not migrated.  This would cause the
value to default to 0, causing login failures for existing users.
=> Fix migration of hashversion

src/common/signalproxy.cpp
_id was used to index SignalProxy::SignalRelay::_slots.
signal.signalId is used to index caller->metaObject()->method.
This can be verified by changing eg. displayMsg to use a type that is
compatible with Message but won't work with QMetaType::type, like Message&
=> signalproxy: Correct signal method name warnings

CMakeLists.txt
OSX uses another backend than OpenSSL according to someone on #qt, so we shouldn't check for it in cmake. Instead we should only check if `QT_NO_SSL` is defined and do runtime checks with `QSslSocket::supportsSsl()` (which I still have to do in all the right places).
=> Fix the SSL check on systems that don't use OpenSSL

src/common/aliasmanager.cpp
The `/wait` check is to test if the first command is a `/wait`, which would operate synchronously.
But `/wait` matches also on other commands – so, if, for example, we’d have a command like `/waiting`, it would be matched.
Instead we actually want to match on `/wait_ ` (with space at the end, the `_` is supposed to represent a space).
=> Fixed a tiny bug in aliasmanager

src/common/eventmanager.h, src/common/ircchannel.cpp, src/common/ircuser.cpp, src/core/corenetwork.cpp, src/core/corenetwork.h, src/core/coresessioneventprocessor.cpp, src/core/coresessioneventprocessor.h, src/core/ircparser.cpp
* Support IRCv3 capability negotiation, allowing for more than just SASL
* Opt-in to immediate notification of away messages for other users
* No need for ```WHO``` polling, works on arbitrarily large channels
* Get away messages without ```WHOIS```
* Add more sources of nick information updates (```nick!user@host```)
* Track multiple user modes instead of just the highest, e.g. ```qohv``` instead of ```q```
Modern chat systems such as Jabber and Telegram provide multiple ways to indicate status and presence, raising expectations for all conversation platforms.
IRC offers two forms of status, "Here" or "Gone", with an optional message for the latter.  Quassel's current approach requires polling ```WHO``` to update presence information, introducing minutes of delay between updates for …
=> Implement IRCv3.2 CAP LS, away-notify and friends

CMakeLists.txt
If a core was built with a dirty working tree, -dirty will be appended
to the version string. Interestingly, we already test for this in
quassel.cpp (line 292), but this was not being added in the cmake phase.
=> Include dirty status in core information

src/common/aliasmanager.cpp
"/ /asdf" now works the same as "//asdf". This is just a convenience for
those of us used to irssi habits, which tend to die hard. :)
=> Make "/ " use the rest of the message as a literal

src/common/ircchannel.cpp, src/core/corenetwork.h, src/core/coresessioneventprocessor.cpp
Channel-specific user modes in ```IrcChannel``` should not be applied to ```IrcUser``` objects shared between channels.  Otherwise, this results in getting ```+o``` operator status in one channel implying ```+o``` in other channels.  Fortunately, only tooltips seem affected.
User modes shown in the nick list of Quassel should instead check the current channel user modes in ```IrcUserItem::toolTip()```, perhaps as part of pull-request #186.
=> Don't update IrcUser modes with channel-specific modes

src/qtui/qtuiapplication.cpp, src/qtui/qtuiapplication.h
Qt5 moved away from virtual methods towards signals for commitData() and saveState().
These were simply not called anymore in our code.
In Qt 5.6 a bug was fixed that broke session management at least with KF5.
As we do handle the session management, we can safely disable the fallback.
See QTBUG-49667 and https://codereview.qt-project.org/#/c/148274/ for details.
Please test this with Qt4 as I don't have a setup for it anymore.
Applying this patch allows my local KDE 5.12.3 to successfully restore quasselclient built against Qt 5.6.0. I also verified that it actually uses the session restoring code path in resumeSessionIfPossible().
=> Support session management with Qt5

CMakeLists.txt, src/client/clientauthhandler.cpp, src/common/quassel.cpp, src/common/quassel.h, src/core/coreauthhandler.cpp, src/core/corecoreinfo.cpp, src/core/coresessioneventprocessor.cpp, src/qtui/aboutdlg.cpp, src/qtui/coreinfodlg.cpp, src/qtui/ui/coreinfodlg.ui, version.h.in
Alternative to and based on PR #127
This makes it possible to create reproducible builds.
Here using the git-commit date instead of a dummy date
See also:
https://wiki.debian.org/ReproducibleBuilds/About
Because I'm not yet very familiar with cmake and c++ please double check:
* that I didn't overlook something and _buildInfo.commitDate was really not used! (changed from uint to QString)
* that the change to CMakeLists.txt is ok...
=> Replace build date with commit date (Alternative to #127)

CMakeLists.txt
The check in qglobal.h requires _only_ -fPIC, if -fPIE is defined the check fails for GCC 5 and above. To avoid linking against QtCore we also need to define QT_NO_VERSION_TAGGING.
=> Fix the SSL check with Qt 5.6 and GCC 5

.gitignore, src/client/networkmodel.cpp, src/common/CMakeLists.txt, src/common/eventmanager.h, src/common/irccap.h, src/common/ircuser.cpp, src/common/ircuser.h, src/common/network.cpp, src/common/network.h, src/common/quassel.h, src/core/corenetwork.cpp, src/core/corenetwork.h, src/core/coresessioneventprocessor.cpp, src/core/coresessioneventprocessor.h, src/core/eventstringifier.cpp, src/core/eventstringifier.h, src/core/ircparser.cpp
* Support ```CAP NEW``` and ```CAP DEL``` as [required by IRCv3 specs](http://ircv3.net/specs/extensions/cap-notify-3.2.html )
* Needed to remain [listed as IRCv3.2 compliant](http://ircv3.net/software/clients.html ), used to handle services restarting, etc
* Synchronize IRCv3 capabilities between core and client
* Backwards-compatible, allows for smarter client suggestions
* Synchronize nick services accounts (NickServ/SASL), part two of [```account-notify```](http://ircv3.net/specs/extensions/account-notify-3.1.html )
* Now that [pull request #186](https://github.com/quassel/quassel/pull/186 ) is merged, display client-side when available
*  Add Feature flag ```CapNegotiation = 0x0020```
* Support [the ```CHGHOST``` capability](http://ircv3.net/specs/extensions/chghost-3.2.html )
* …
=> Sync IRCv3, account tracking, CAP NEW/DEL, polish, and more!

src/core/SQL/PostgreSQL/20/select_messagesNewerThan.sql
* Fix the PostgreSQL `select_messagesNewerThan` statement limiting to the wrong buffer
* Replace use of message ID `$1` for `bufferid` in inner `SELECT` with the actual buffer ID, `$2`
* Fixes using the wrong buffer for `lastmsgid` limit, resolving missing messages with unread fetching
* Fixes regressions from [pull request 273](https://github.com/quassel/quassel/pull/273 ), missed in [pull request 274](https://github.com/quassel/quassel/pull/274 )
Impact | ★★★ *3/3* | Fixes missing messages with Postgres unread backlog fetching
Risk | ★☆☆ *1/3* | Variable change shouldn't break more, risk accepted in previous PRs
Intrusiveness | ★★☆ *2/3* | Minor schema change, might interfere with other pull requests
*Apologies for missing this …
=> core: Fix Postgres messagesNewerThan wrong buffer

src/core/SQL/PostgreSQL/20/update_buffer_lastseen.sql
GH-273 introduced a workaround for the issue where sometimes the
lastseenmsgid for a buffer was set to a msgid not in that buffer.
However, the workaround was incorrect as the "min()" function in
PostgreSQL is an aggregate function for use on a column, not a
function to return the least of a list of values passed in.  The
correct function for use here is "least()".
=> Fix lastseenmsgid updates in PostgreSQL

src/common/main.cpp, src/core/SQL/PostgreSQL/select_all_authusernames.sql, src/core/SQL/PostgreSQL/select_authusername.sql, src/core/SQL/SQLite/select_all_authusernames.sql, src/core/SQL/SQLite/select_authusername.sql, src/core/core.cpp, src/core/core.h, src/core/coreapplication.cpp, src/core/coresession.cpp, src/core/coresession.h, src/core/oidentdconfiggenerator.cpp, src/core/oidentdconfiggenerator.h, src/core/postgresqlstorage.cpp, src/core/postgresqlstorage.h, src/core/sql.qrc, src/core/sqlitestorage.cpp, src/core/sqlitestorage.h, src/core/storage.h
This mode is disabled by default.  When specified, this restricts
authoratative ident responses to be the authuser account name.
This is a cut-down version of,
https://github.com/quassel/quassel/pull/164 which was originally
authored by @esainane.  @AlD requested that the database schema
change be removed, but the request fell dormant and was eventually
closed.  This version removes the schema change as requested,
always using the user's core username as the ident when enabled.
Co-authored-by: Sai Nane <esainane+github@gmail.com>
Co-authored-by: Michael Marley <michael@michaelmarley.com>
=> Add strict-oidentd mode

src/common/highlightrulemanager.h
- Previously, sync calls included the new HighlightNickType
- This causes deserialization trouble in older clients
- Now int is used, and the data is static_cast'd back and forth
This breaks compatibility with 0.13 clients and cores from the past months, and restores compatibility with 0.12.4 or older clients.
=> Fixes the Highlight Rule Manager

src/common/main.cpp, src/common/quassel.cpp, src/core/coreapplication.cpp
Initialize logging earlier, so output during core initialization
gets routed properly.
Enable the logging options also for quasselclient; there's no good
reason to limit this to the core and monolithic client. However, as
a side-effect, the default log level is now Info also for the client,
so "-l Debug" must be specified on the command line to get debug
output.
=> Improve logger configuration

src/qtui/mainwin.cpp, src/qtui/mainwin.h, src/qtui/settingspages/networkssettingspage.cpp, src/qtui/settingspages/networkssettingspage.h, src/uisupport/contextmenuactionprovider.cpp, src/uisupport/networkmodelcontroller.cpp, src/uisupport/networkmodelcontroller.h
This adds a menu item of 'Configure' to the right-click menu for a Network in the buffer list.
Clicking on 'Configure' will open the Configure Networks dialog to the respective Network's settings.
**Use-Case:** 
* Large network lists, when you need to make a change to a network...it's now just a click away instead of going through the Main Menu or the Main Settings dialog.
* Continuous modification of Networks, ie: IRC Development, TestNets, etc.
**Impact:**
* 'Configure' is added above 'Disconnect/Connect', this could cause some users to re-learn habits if they are very used to using the 'Disconnect/Connect' items in this menu.
**Testing:**
Tested this with:
* A single, connected Network (as seen below)
* A single, disconnected Network
* Multiple Networks, both connected and disconnected …
=> Add 'Configure' to the right-click Menu of a Network in the buffer list

src/client/clientignorelistmanager.cpp, src/client/clientsettings.cpp, src/common/highlightrulemanager.cpp, src/common/ignorelistmanager.cpp, src/common/ignorelistmanager.h, src/common/util.cpp, src/common/util.h, src/qtui/qtuiapplication.cpp, src/qtui/qtuimessageprocessor.cpp, src/qtui/settingspages/corehighlightsettingspage.cpp, src/qtui/settingspages/corehighlightsettingspage.h, src/qtui/settingspages/corehighlightsettingspage.ui, src/qtui/settingspages/highlightsettingspage.cpp, src/qtui/settingspages/highlightsettingspage.h, src/qtui/settingspages/highlightsettingspage.ui, src/qtui/settingspages/ignorelisteditdlg.ui
* Unify highlight and ignore channel matching
* Add `!` syntax to ignore list scope matching
* Switch highlight rule scope matching to same as ignore list
* Make `RegEx`, `CS` also apply to `Sender` and `Channel`
* Breaks existing advanced highlight rules, but local rules are **migrated on upgrade**
* Almost no functionality lost, see examples
* Highlight current nick by default on upgrade/new configuration
* For remote highlights, specify `CurrentNick` as default
* For local highlights, specify `NoNick` as default
* Fix up importing local highlights
* Prompt before importing, show success afterwards
* Fix import button not working
* Explain highlights and Local vs. Remote highlights
* Add tool-tips to the highlight/ignore list box and other elements
* Indicate 'local' is for this device …
=> common: Polish core-side highlights

src/common/main.cpp, src/core/core.cpp, src/core/core.h, src/core/corenetwork.cpp, src/core/coresession.cpp, src/core/coresession.h, src/core/oidentdconfiggenerator.cpp, src/core/oidentdconfiggenerator.h, src/core/sessionthread.cpp, src/core/sessionthread.h
* Let strict ident mode apply to normal ident responses, too
* Allows using it with IRC networks that don't check for identd replies
* Simplifies limiting ident responses if identd is not required
* Follows functionality already available in ZNC
* Clean up matters
* Rename `--oidentd-strict` to `--strict-ident`, to better match the functionality
* Simplify functions
Impact | ★★☆ *2/3* | Consistency, requirement for shared core on some networks
Risk | ★★☆ *2/3* | Easily reverted, potential complaints over ident vs identd
Intrusiveness | ★★☆ *2/3* | Command line flag changes, could interfere with other PRs
Networks need a fixed identifier to ban troublesome users.  For shared Quassel installations, banning by IP address is not …
=> core: Rename strict-ident, apply to non-identd response

src/common/ircchannel.cpp, src/common/network.cpp, src/common/network.h
* Keep per-channel user modes sorted by priority
* Sort by `prefixModes()` priority when adding/setting channel modes
* Enables showing only the highest sender prefix to work
Impact | ★★☆ *2/3* | Fixes user-facing misleading display of sender modes
Risk | ★★☆ *2/3* | Might break user channel modes, potential performance penalty
Intrusiveness | ★☆☆ *1/3* | Minor changes, shouldn't interfere with other pull requests
*Thanks to @justJanne for finding the issue!*
Quassel offers a way to prefix the channel mode to the nickname, e.g. `@nickOp` and `+nickVoice`.  With IRCv3 `multi-prefix` enabled, it's possible to see all applied modes instead of just the highest, but Quassel still allows for only seeing the highest while storing all …
=> common: Fix out-of-order user prefix channelmodes

src/core/coresessioneventprocessor.cpp
* Specify timezone in `CTCP TIME` replies
* Simplifies figuring out what timezone someone's in
* Minimal privacy risk as timezone could be determined before by comparing with UTC
* All of `CTCP` can be ignored as before
Impact | ★☆☆ *1/3* | User-facing enhancement to rarely-used `CTCP TIME`
Risk | ★☆☆ *1/3* | Possible wrong formatting of `CTCP TIME` replies
Intrusiveness | ★☆☆ *1/3* | Minor changes, shouldn't interfere with other pull requests
*Thanks to `wink` for finding the issue!*
`CTCP TIME` offers an easy way to get an idea of what time it is for someone else, useful to avoid waking them up or otherwise trying to align schedules.
Quassel already provided local time (*of the Quassel core*), but did not include timezone …
=> core: Fix CTCP TIME not specifying timezone

src/common/aliasmanager.cpp, src/qtui/settingspages/aliasesmodel.cpp
* Add `$i:identd` parameter to aliases
* Represents `ident` if verified, or `*` if unknown or unverified
* Allows ban rules to respect identd, e.g. `/mode $channel +b *!$1:identd@$1:hostname; /kick $1`
* Replace empty nickname parameters with `*`
* Using the variables for nicknames before `WHO`'ng them still provides results
* May be dangerous if using above ban example on nickname without hostname available
* Update alias configuration tooltips
* Add `identd`
* Organize everything into a table
* Update comments
Impact | ★★☆ *2/3* | User-facing moderator improvement, tooltip cleanups
Risk | ★★☆ *2/3* | Possible confusion, small behavior change to existing aliases
Intrusiveness | ★☆☆ *1/3* | Minor changes, shouldn't interfere with …
=> common: Add '$i:identd' verified ident alias, polish

src/core/abstractsqlstorage.cpp
* Update `schemaversion` for each successful intermediate upgrade
* Better chance of auto-recovering by running core after interrupt
* Aids debugging after the fact
* Makes downgrades after interrupted upgrade more explicit, requiring setting schema version
* Update logging to be more explicit about what schema version fails
Impact | ★★★ *3/3* | Reduces risk of breaking database with interrupted upgrades
Risk | ★★☆ *2/3* | Schema version might not be stored correctly
Intrusiveness | ★☆☆ *1/3* | Minor changes, shouldn't interfere with other pull requests
When running upgrade queries, update the schema version for each intermediate step.  This ensures that any interrupted upgrades have a greater chance of resuming correctly after …
=> core: Save schema version for intermediate steps

src/qtui/inputwidget.cpp, src/qtui/inputwidget.h, src/qtui/mainwin.cpp, src/qtui/mainwin.h, src/qtui/ui/inputwidget.ui
* Add keyboard shortcuts for formatting
* <kbd>Ctrl+B</kbd>, <kbd>Ctrl+I</kbd>, <kbd>Ctrl+U</kbd> for **bold**, *italic*, and `_underline_` (*imagine that one*)
* <kbd>Ctrl+Shift+G</kbd> and <kbd>Ctrl+Shift+B</kbd> applies selected foreground or background color, respectively
* <kbd>Ctrl+Shift+C</kbd> clears formatting of selected text
* All shortcuts customizable, like the other shortcuts
* Polish formatting UI
* Add button to clear formatting
* Add tooltips to make it more accessible
* Remap `Reload Stylesheet` from <kbd>Ctrl+R</kbd> to <kbd>Ctrl+Shift+R</kbd>
* Avoids conflict with default `Set Marker Line`, <kbd>Ctrl+R</kbd>
* Can be customized as usual
* Clean up comments
Impact | ★★☆ *2/3* | User-facing requested feature, …
=> client: Add formatting shortcuts, polish

src/qtui/settingspages/corehighlightsettingspage.cpp, src/qtui/settingspages/highlightsettingspage.cpp
*For sake of time, pull request kept simple.  Will add more documentation later if needed.*
Rename `Local Highlights` as `Legacy Highlights`, and rename `Remote Highlights` as plain `Highlights`.  Update the info-bar text and other references as appropriate.
This reduces confusion over which highlights to configure in Monolithic mode.
=> mono: Move Local Highlights -> Legacy Highlights

src/qtui/settingsdlg.cpp, src/qtui/ui/settingsdlg.ui
We've suffered from the page tree in the settings dialog being
squashed horizontally for a long time. A previous commit (65c463f0)
tried to fix this by calculating a minimum size and explicitly
resizing the dialog, but this didn't properly work at least on HIDPI
displays.
Instead, fix layouting properly by setting the correct size policy
for the tree widget, and removing both the afforementioned workaround
and a previous hack that tried to set the minimum width manually
(and failed due to a still-hidden widget reporting wrong size hints).
=> Properly fix the SettingsDlg layout

src/qtui/CMakeLists.txt, src/qtui/mainwin.cpp, src/qtui/settingspages/appearancesettingspage.ui, src/qtui/systrayanimationnotificationbackend.cpp, src/qtui/systrayanimationnotificationbackend.h, src/qtui/systraynotificationbackend.cpp
First attempt at fixing this: PR #328 
**Problem**
With the change from PR #139 the update to the new Snore Notification Backend modified the behaviour of loading the SystrayNotificationBackend if Snore is enabled.
See: https://github.com/quassel/quassel/commit/79ef34a9495187b296dd554cf57983019001c38b#diff-cfff7c7c664d451740ea7bda9372fc10L83
Although it makes sense to not show a message bubble if snore is enabled, the tray icon animation is handled by SystrayNotificationBackend too.
Additionally, (in my opinion) having KDE should not stop you from allowing the Tray icon to be animated …
~(This might be the issue of https://bugs.quassel-irc.org/issues/1383 but I'm not sure.)~
**Solution**
In order to fix this, the animation trigger from SystrayNotificationBackend now got split away into …
=> (Re-)enable Trayicon blinking with Snore (still not working with KDE)

src/qtui/chatviewsettings.h, src/qtui/qtuiapplication.cpp, src/qtui/qtuistyle.cpp, src/qtui/qtuistyle.h, src/qtui/settingspages/chatviewsettingspage.cpp, src/qtui/settingspages/chatviewsettingspage.h, src/qtui/settingspages/chatviewsettingspage.ui, src/qtui/settingspages/corehighlightsettingspage.ui, src/uisupport/settingspage.cpp, src/uisupport/settingspage.h, src/uisupport/uistyle.cpp, src/uisupport/uistyle.h
* Optionally show only the highest sender mode prefix
* `All modes`, `Highest mode` (**new default**), `No modes` (**migrated default**)
* Keep existing users on no modes to match old behavior
* Use highest mode for new configuration to match other clients
* *`0.13-master` users will need to re-enable sender prefixes after this*
* Clean up and improve settings page handling
* Fix `SettingsPage::hasChanged()` widget-specific handling, support `FontSelector`
* `ChatViewSettings` check if needing to reload stylesheet before doing it
* Fix settings migration unintentional fallthrough
Impact | ★★☆ *2/3* | User-facing requested feature, fixes bugs
Risk | ★★☆ *2/3* | More options to manage, possible settings regressions
Intrusiveness | …
=> client: Option for highest sender mode

CMakeLists.txt, INSTALL, cmake/QuasselCompileSettings.cmake
Check for the existence of the ccache binary, and enable ccache
support if available. This avoids the need for hacks using PATH
or the CXX variable to make ccache work.
The automatic detection can be disabled by passing -DUSE_CCACHE=OFF
to CMake (may be useful for distributors having their own ccache
infrastructure in place).
Reorder things in the top-level CMakeLists.txt a bit, because ccache
should be enabled before calling project() (which checks compiler
settings).
=> cmake: Enable ccache by default, if available

README.md
* Add more guidance
* Document the use of `--help`
* Add a section on official downloads, automated builds, and community-contributed builds
* Update and simplify README for visual and plain-text reading
* Move status badges to a new line, clean up URLs
* Add `Windows:` text [to AppVeyor badge](https://www.appveyor.com/docs/status-badges/ ) to distinguish (*[no option on Travis CI](https://docs.travis-ci.com/user/status-images/ )*)
* Replace ` ```triple-backticks``` ` with ``` `single-backticks` ```, easier to read
* Move CI status URLs out of the way using Markdown references
* Remove outdated notice about `manageusers.py`
* Fix bulleted list at the bottom
Impact | ★☆☆ *1/3* | Developer-facing polish, clarifications
Risk | ★☆☆ …
=> docs: Simplify README.md, add help, downloads

README.md, src/core/SQL/README.md, src/core/SQL/updateSQLResource.sh, src/core/SQL/upgradeSchema.sh
* Migrate SQL schema documentation to new `README.md`
* Add an introduction section
* Add a pointer to wiki documentation
* Move the comments from `upgradeSchema.sh` into Markdown-formatted `README.md`
* Change Unicode `–` to ASCII `--` in root `README.md`
* Easier to distinguish in monospace text environments.
Impact | ★★☆ *2/3* | Developer-facing polish, documentation for pitfalls
Risk | ★☆☆ *1/3* | Possible confusion, easily reverted
Intrusiveness | ★☆☆ *1/3* | Only changes `README.md`, shouldn't interfere with other pull requests
*Note: Looking at [the branch directly](https://github.com/digitalcircuit/quassel/blob/ft-readme-tweaks-sql/src/core/SQL/README.md ) may be easier than using GitHub's pull request difference view.* …
=> docs: Add SQL README.md, fix up formatting

src/uisupport/uistyle.h
* Use `QT_VERSION` macro for `UiStyle` `enum class` fallback
* Makes it simpler to clean up Qt4 code once the migration happens
* Mimics how it's done in `quassel.h` for the `Feature` enum
_As this is a trivial change, I've skipped the usual breakdown and analysis.  Only risk should be differences in Qt5 and Qt4 handling._
=> client: Use QT_VERSION for 'enum class' fallback

src/client/coreaccount.cpp, src/client/coreaccount.h, src/client/coreaccountmodel.cpp, src/client/coreaccountmodel.h, src/qtui/settingspages/coreaccountsettingspage.cpp
* Fix Remote Cores wrongly being marked as unsaved on load
* Happens if default core account was chosen and index in `QComboBox` was not `0`
* Clean up `CoreAccount`/`CoreAccountModel`, add `qDebug` support
* Not needed, but since it was added while debugging this, worthwhile keeping
* Add inequality `!=` operator to simplify comparisons elsewhere
Impact | ★★☆ *2/3* | User-facing fix for misleading configuration prompt
Risk | ★☆☆ *1/3* | Might not correctly detect core account changes
Intrusiveness | ★☆☆ *1/3* | Minor changes, shouldn't interfere with other PRs
1.  Start with blank client configuration
2.  Add two accounts, `A` and `B`, with any data
3.  Pick `B` as default account
4.  Save, close configuration dialog, re-open
5. …
=>  client: Fix Remote Cores marked unsaved on load, cleanup

src/common/highlightrulemanager.cpp, src/common/highlightrulemanager.h, src/core/corehighlightrulemanager.h, src/qtui/settingspages/corehighlightsettingspage.cpp, src/qtui/settingspages/corehighlightsettingspage.h
- Sync highlightNick and nicksCaseSensitive as actual Q_PROPERTY
- Identify rules by their id, not their name
- This allows multiple rules to have the same rule, but different scopes
and senders
This breaks the protocol with existing 0.13 clients. They can still connect, but cannot configure highlight rules.
=> Cleans protocol for highlight rules

src/core/corenetwork.cpp, src/core/corenetwork.h, src/core/coresessioneventprocessor.cpp, src/core/eventstringifier.cpp
* Accept both 1 and 2 parameter `PONG` replies
* Take the last parameter of either for timestamp calculation
* Handles both `:localhost PONG 02:43:49.565` and `:localhost PONG localhost :02:43:49.565`
* Silence `PING` replies for invalid timestamps on servers that don't quote for `PONG`
* Track if server sends valid timestamps; if not, hide next `PONG` after automated `PING`
* Avoids spamming the server window with unwanted timestamps
* Helps with [`irc.gitter.im`](https://irc.gitter.im), among others
Impact | ★★☆ *2/3* | User-facing `PING` improvements, fix single-parameter server
Risk | ★★☆ *2/3* | `PONG` replies may be hidden or shown at the wrong time
Intrusiveness | ★☆☆ *1/3* | Small set of changes, shouldn't interfere with …
=> core: Handle single-param PONG replies, hide bad timestamps

src/client/client.cpp, src/client/client.h, src/common/coreinfo.cpp, src/common/coreinfo.h, src/common/quassel.h, src/qtui/coreinfodlg.cpp, src/qtui/coreinfodlg.h
* Synchronize core info before first connect
* Removes warning about missing receiver for core info signal
* Refresh legacy core info whenever opening Core Info dialog
* On legacy cores, fetch core information by recreating `CoreInfo` object
* Add feature flag `SyncedCoreInfo`, don't poll on modern cores
* Fixes information only refreshing once when connecting
* Indicate in core info dialog when disconnected
* Reduces confusion about state of the core
* Before, core info dialog would simply stop updating
Impact | ★★☆ *2/3* | User-facing polish, better client experience for old cores
Risk | ★★☆ *2/3* | Core Info might stop being refreshed, become corrupted
Intrusiveness | ★★☆ *2/3* | Protocol changes, could interfere with other PRs …
=> client: Handle legacy CoreInfo, fix sync, disconnect

src/uisupport/aboutdata.cpp
* Rename @justJanne 's `QuasselDroid` to `Quasseldroid`
* Matches [upstream branding rename](https://git.kuschku.de/justJanne/QuasselDroid-ng/commit/5e08f048764171d550ce17127c4075709bf9c2cd ) (*to reduce risk of lawsuit over `Droid`*)
* Other mention of `QuasselDroid` from `sandsmark` left alone, as that project's not renamed
*As this is a trivial change, I've skipped the usual breakdown and analysis.  Only risk should be incorrect about data - feel free to comment here or correct afterwards.*
=> aboutdata: Rename QuasselDroid → Quasseldroid

src/qtui/inputwidget.cpp
* Fix issue where sometimes text shortcuts could not change formatting
* When toggling text formatting via keyboard, always update button state
* Fixes issue where formatting could not be removed by shortcut, only by button
Impact | ★★☆ *2/3* | User-facing edge case where keyboard shortcuts break
Risk | ★☆☆ *1/3* | Possible mismatch between format state and actual text
Intrusiveness | ★☆☆ *1/3* | Minor changes, shouldn't interfere with other pull requests
*Note: I originally avoided doing this out of concern it'd create a loop with the `clicked()` signal firing when setting check state.  Thankfully that's not the case.*
1.  Type `test message here`
2.  Select `message`, mark as italic (*button or shortcut*)
3.  Move cursor to end …
=> client: Fix text format shortcuts edge case

src/core/coreuserinputhandler.cpp
Currently when running `/mode ...` without having a valid channel name or our current IRC nick as the first parameter, the current buffer name is prepended. This works great when running from a channel buffer or a user query (typically changing modes of other users will fail, but that's not a Quassel problem).  
When ran from the status buffer, the buffer name returned is an empty string, so we can check for this and prepend our current IRC nick to be able to shortcut (for example: `/mode +R`) from the status buffer. This does not effect the channel/user prepending as mentioned before.
**Before:**
From channel: `/mode +R` ; Mode +R is set on the channel
From user query: `/mode +R` ; Server returns `Can't change mode for other users`
From server query: `/mode +R` ; Server returns `<server …
=> /mode: Prepend current nickname if buffer has no name

src/common/quassel.cpp, src/qtui/settingspages/networkssettingspage.ui
=> common: Use UTF-8 server encoding by default

src/core/corenetwork.cpp, src/core/oidentdconfiggenerator.cpp, src/core/oidentdconfiggenerator.h
* Update `OidentdConfigGenerator` signal connections, adding missing `socketId`
* Added [in integrated `identd` commit, 41b9d68](https://github.com/quassel/quassel/commit/41b9d689945e784b160a25d12076600ff4b7ae90 )
* Fixes `oidentd` breakage, warning about signals/slots not matching up
* Clean up line length and spacing
Impact | ★★★ *3/3* | Fix `oidentd` signal/slot issues, avoid lengthy warning messages
Risk | ★☆☆ *1/3* | Signal/slot usage might be incorrect
*Thanks to @genius3000 for finding this issue!*
**Command used**
```
./run-profile.sh master core local --oidentd --oidentd-conffile /tmp/test
```
*Two pairs of warnings for each …
=> core: Fix oidentd signal connection, cleanup

src/common/main.cpp
The value for the option identifier was missing, causing what was
intended to be the default value to actually become the identifier
and the default value to be undefined.  This resulted in random
ports being chosen.
=> Fix default port for integrated ident daemon

src/common/settings.cpp
* Remove cache check in `Settings::localKeyExists()`
* Fixes settings upgrade skipping steps due to earlier steps caching default (*not stored*) values
* Notably, creating/writing the `QtUiStyle` settings Qt StyleSheet.
* Symptoms only visible when migrating multiple steps at once
* Fixes bug introduced [with migration logic in pull request #185](https://github.com/quassel/quassel/pull/185 )
Impact | ★★☆ *2/3* | Avoids user-facing unexpected UI changes on upgrade
Risk | ★☆☆ *1/3* | Possible wrong settings defaults
1.  Clear Quassel client configuration
2.  Restore a valid `0.12.5`-era configuration file, or use dummy file, below
3. …
=> client: Fix settings upgrade missing some steps

src/client/client.h, src/client/clientuserinputhandler.cpp, src/qtui/channellistdlg.cpp, src/qtui/channellistdlg.h, src/qtui/mainwin.cpp, src/qtui/mainwin.h, src/uisupport/networkmodelcontroller.cpp, src/uisupport/networkmodelcontroller.h
* Pass `/list <params>` to channel list dialog when opening
* Allows for `/list #channel` to search
* Restores behavior similar to current stable release
* Immediately search when called via `/list` and `/list <params>`
* Mimics behavior of non-UI `/quote list`
* Polish up the experience
* Add more keyboard friendliness with input focus
* Sort channels in ascending order by default
* Prompt when `/list` called without valid network selected
* Fixes `/list` before any network selected resulting in useless channel list dialog
* Happens when `/list` after connecting to core without any connected networks
Impact | ★★☆ *2/3* | User-facing regression fix, UI polish/keyboard readiness
Risk | ★☆☆ *1/3* | Channel list may not show at …
=> client: Convert /list #chan to advanced search, auto-search, polish

src/common/bufferviewconfig.cpp, src/common/bufferviewconfig.h
* Fix initialization of default values when upgrading `BufferViewConfig`
* Fixes wrongly enabling persistent buffer search on upgrade
* Matches defaults for fresh configuration
* Avoids cluttering the UI for upgrades, less likely to get complaints
* Can still enable in the settings UI as before, or use keyboard shortcut
* Add more documentation
Impact | ★★☆ *2/3* | Avoids user-facing unexpected UI changes on upgrade
Risk | ★☆☆ *1/3* | Possible wrong `BufferViewConfig` defaults, broken loading
*Polishes [changes made in pull request #190](https://github.com/quassel/quassel/pull/190).*
1.  Set up Quassel core `0.12.5`
2.  Connect with a …
=> common: Fix buffer search wrongly showing on upgrade

src/core/coreirclisthelper.cpp, src/core/coreirclisthelper.h
The current timer of 10 seconds from starting the channel list query can timeout with larger lists or strict rate-limiting. This will cause an early 'end of list' which populates the dialog in the client with what was received up till then and the client dumps the rest to the Status Buffer. The timer also isn't killed when a proper 'end of list' is received and a new query ran quickly after another can be timed out by a previous timer.  
I found `QBasicTimer` to be a better fit here as calling `start(ms)` will restart the timer if it's already running. This allows us to restart the timer after each call to `addChannel()`, letting the query take a little longer if needed but not timing out while still receiving data. The timer is now removed when a proper 'end of list' is received and a …
=> Change the timer method for /LIST to handle large lists better

src/qtui/chatmonitorfilter.cpp, src/qtui/chatmonitorfilter.h, src/qtui/settingspages/chatmonitorsettingspage.cpp, src/qtui/settingspages/chatmonitorsettingspage.ui
Add an option to the chat monitor to always show own messages, similar to how highlights can be shown always.
=> Chat Monitor: Add option to always include own messages

src/qtui/settingspages/chatmonitorsettingspage.ui
* Rename 'always show own messages' option to `Include ignored buffers`
* Previously titled `Always`
* Matches the option `Include read messages`
A quick test also confirms this functionality works compared to my defaults before.  No extensive testing done.
No functional change, just minor UI tweak before string freeze.
=> chatmonitor: "Always" → "Include ignored buffers"

src/core/corehighlightrulemanager.cpp, src/core/corehighlightrulemanager.h, src/qtui/settingspages/corehighlightsettingspage.cpp
* Modernize `CoreHighlightRuleManager` via `SyncableObject` functions, following `DccConfig`
* Fixes highlight nick configuration being reset on core/monolithic restart
* Simplifies code
* Fixes regression from [highlight protocol pull request #370](https://github.com/quassel/quassel/pull/370 )
* Save remote highlight rules if changed before importing local
* Fixes losing unsaved rules when importing
Impact | ★★★ *3/3* | User-facing common functionality - remembering highlight nick options
Risk | ★★☆ *2/3* | Core-side change, revertible with configuration loss
Persistence for **`Highlight Nicks`** is needed, for otherwise restarting the …
=> core: Fix highlight nick config save/load

src/client/client.cpp, src/client/client.h, src/common/main.cpp, src/common/types.h, src/core/core.cpp, src/core/core.h, src/core/coreapplication.cpp, src/core/coreapplication.h, src/qtui/mainwin.cpp, src/qtui/mainwin.h, src/qtui/monoapplication.cpp, src/qtui/monoapplication.h, src/qtui/qtuiapplication.cpp, src/qtui/qtuiapplication.h
Since the event loop may not be running while the core is being
initialized, calling exit() does not have the desired effect.
Instead, throw an exception with exit code and error message to
be able to handle this correctly. Exceptions must not be thrown
through the event loop, so ensure that they're caught before in
cases where the event loop was started already.
For the monolithic client, introduce an asynchronous init method
that catches potential exceptions and calls exit() instead. Show
an error popup in the UI if an error message is provided, so the
user gets some feedback before the client is terminated.
=> Improve handling of core initialization errors

src/common/highlightrulemanager.cpp, src/qtui/settingspages/corehighlightsettingspage.cpp, src/qtui/settingspages/corehighlightsettingspage.h, src/qtui/settingspages/highlightsettingspage.cpp
* Allow empty `Name` for core-side highlights
* Allows for matching all messages by setting `Name` to empty
* Combine with `Sender` and `Channel` to match all from a nick/buffer
* Removes the need for regular expressions just to match all messages
* Update tooltips to explain
* Clarify `Channel` column tooltip functionality
* Actually refers to buffer name, so mention `channel/query` in tooltip
* Don't rename column as queries trigger highlights by default, less useful
* Polish settings page UI
* Unify tooltips, fixing an outdated tooltip for `Highlight Ignore Rules`
* Set `Sender` column to auto-resize, like other columns
* Deduplicate code, simplifying future tooltip changes
Impact | ★★☆ *2/3* | User-facing requested feature, …
=> common: non-RegEx match all highlights, simplify UI

CMakeLists.txt, src/qtui/inputwidget.cpp, src/qtui/inputwidget.h, src/qtui/settingspages/inputwidgetsettingspage.cpp, src/qtui/settingspages/inputwidgetsettingspage.ui, src/uisupport/CMakeLists.txt, src/uisupport/multilineedit.cpp, src/uisupport/multilineedit.h
Apparently, Sonnet, when used standalone (i.e. not in KTextEdit),
does not honor its own setting to disable it by default.
Explicitly read the setting when initializing the highlighter, and
set its active state accordingly. Provide a context menu option
to enable/disable spell check on-the-fly as well.
Remove the bogus/unused checkbox in the InputWidget settings page;
there is a dedicated settings page for configuring spell checking.
Explicitly depend on Sonnet when building with KDE Frameworks
(it was transitively depended upon anyway), so we can be sure to
offer the Sonnet settings page even when using Frameworks.
=> Allow to disable spell checking

src/uisupport/fontselector.cpp
By default Qt uses a different (native) font selection dialog on OSX.
But that one does not change the selected font when clicking OK.
With this PR we tell Qt to open the normal Qt font dialog instead of the native one.
=> Use Qt's font dialog instead of the (broken) native OSX one

src/core/coresessioneventprocessor.cpp, src/core/eventstringifier.cpp, src/core/sqlitestorage.cpp, src/qtui/bufferwidget.cpp, src/qtui/chatscene.cpp, src/uisupport/networkmodelcontroller.cpp, src/uisupport/tabcompleter.cpp
These cause warnings in most compilers, so remove them again until
we can use C++17 and the official attribute.
Add comments, so we know the fallthroughs are intentional anyway.
=> Remove [[clang::fallthrough]] annotations again

data/stylesheets/default.qss, src/qtui/chatitem.cpp, src/qtui/chatitem.h, src/uisupport/qssparser.cpp, src/uisupport/uistyle.cpp, src/uisupport/uistyle.h
- A new message label "hovered" can now be used in stylesheets to control how a hovered-upon URLs should be rendered. The default stylesheets defines an underline.
- Fix rendering of selected, active clickable. Fixes the issue where a selected URL in a highlighted message would vanished when hovered upon.
- Disable color codes in highlighted messages in the default stylesheet.
=> Stylesheet support for hovered-upon URLs; disable color codes in highlighted messages

src/client/messagefilter.cpp, src/client/messagefilter.h
* Fix duplicate `<nick> has quit` messages in queries
* Search quit message timestamps ±1000 ms, not relying on seconds rounding
* Fixes existing bug made worse by 64-bit time precision in commit 6a63070246d89aa2a2474e3a9a1035fa889ad77e
* Clean up approach
* Don't needlessly track nicknames in hashmap
* Add more documentation
Impact | ★★☆ *2/3* | Fixes user-facing annoying UI regression from `0.12.5`
Risk | ★☆☆ *1/3* | Possibly hiding quit messages or showing too many
*Fixes regression from [changes made in pull request #357](https://github.com/quassel/quassel/pull/357 ).*
Replace the `.contains()` check with `std::binary_search` on …
=> client: Fix duplicated query quit messages

src/common/settings.cpp, src/common/settings.h, src/qtui/chatmonitorfilter.cpp, src/qtui/settingspages/chatmonitorsettingspage.cpp
* Unify `Chat Monitor` defaults
* Syncs three separate places for setting defaults
* Defaults to disabling showing read messages, enabling showing own messages
* Add a comment to explain and hopefully avoid this in the future
* Fix `Settings` default caching wrong values
* Fix caching of default values overriding different defaults elsewhere
* Fixes `Chat Monitor` settings showing up as invalid instead of `Opt Out`
* Cache key persistence, possibly speeding up `localKeyExists()`
Impact | ★★☆ *2/3* | User-facing defaults fix-up, avoids UI quirk
Risk | ★★☆ *2/3* | Different defaults might be used, new cache mechanics
*In `Settings` → …
=> settings: Fix Chat Monitor defaults

src/common/ircuser.cpp, src/common/ircuser.h, src/core/eventstringifier.cpp
* Limit `* User is away` spam to once an hour, or if changed
* Track changes to `away`/`here` state and away message, always showing if those change
* Otherwise, only show duplicate `* User is away` messages once per hour of silence
* `1 hour` delay follows Bitlbee's [`away_reply_timeout` default delay](https://www.bitlbee.org/user-guide.html#set_away_reply_timeout ), albeit is non-adjustable
Impact | ★★☆ *2/3* | Fixes user-facing annoyance, fixes missing changed messages
Risk | ★☆☆ *1/3* | Some might rely on the repetitive spam, delay might be too long
User | Nickname
-----|---------
Quassel user (direct) | `quassel`
Test user (quoted) …
=> core: Limit "User is away" to 1hr or when changed

src/client/networkmodel.cpp, src/client/networkmodel.h, src/client/treemodel.cpp, src/client/treemodel.h
Don't send the dataChanged() signal of PropertyMapItems before actually setting the new value.
Don't store the property list dynamically in every item instance.
=> Fix issues with TreeModel

src/common/main.cpp, src/core/corenetwork.cpp, src/core/corenetwork.h, src/core/ircparser.cpp, src/core/ircparser.h
* Add `--debug-irc` option to core and monolithic builds
* When enabled, sends all raw IRC messages to the log at `Debug` level
* Usually should be combined with `--loglevel Debug`
* Monolithic builds also show messages in `Debug Log` window
* When enabled, puts plaintext IRC passwords in log; be careful on production systems
* Add `--debug-irc-id` option to limit the above to a specific network
* Avoids noise when troubleshooting a specific network without disconnecting all others
* Reduces unnecessary information disclosure on shared cores
Impact | ★★☆ *2/3* | Allows troubleshooting IRC without recompiling Quassel
Risk | ★☆☆ *1/3* | Setting `--debug-irc` puts IRC passwords in debug log
Intrusiveness | ★☆☆ *1/3* | Small set of …
=> common: Add "--debug-irc" to log raw IRC messages

src/core/cipher.cpp
For security reasons (and compatibility to other irc-client's implementations), default to CBC for blowfish encryption.
=> cipher.cpp: Default to CBC instead of ECB

src/common/ircchannel.cpp
Happened to stumble upon this while looking through some issues on the bug tracker. As mentioned in the commit message (below), this isn't crash potential but we shouldn't try to act on a NULL IrcUser.
> Commit e9096505f07fc0c08a7c36f3680c1fde975d4f80 changed the behaviour in joinIrcUsers() from skipping a NULL IrcUser or an already tracked IrcUser to updating the usermodes of said IrcUser. The call to addUserMode() will call isKnownUser() which will log a warning of 'received IrcUser Nullpointer' and return false. This is safe from crashing, but shouldn't be allowed to happen.
=> common/ircchannel: Change to an early continue for a NULL IrcUser

src/common/settings.cpp, src/common/settings.h
Stumbled on this by accident because one particular CI configuration
warned about Settings::localValue() returning a stack reference
(may happen if the default value (which is a const ref itself) is
returned).
Not sure why I don't see this warning in my own setup, but it's
legitimate; thus fix the issue.
=> qa: Don't return a const ref from Settings::localValue()

src/qtui/settingspages/networkssettingspage.cpp
* Fix `Add Network` dialog `OK` button state
* Check if dialog's valid whenever changing `Use preset` and `Manually specify network settings`
* Fixes `OK` button remaining enabled when selecting manual, disabled when selecting preset
Impact | ★☆☆ *1/3* | User-facing clarification of required fields
Risk | ★☆☆ *1/3* | Dialog might not set `OK` state correctly
*In `Configure Quassel…` → `IRC` → `Networks` → `Add…`*
*Notice how when toggling between `Use preset` and `Manually specify network settings`, the `OK` button remains enabled, even though there's no valid network information put in, e.g. `Network name`.*
*In `Configure Quassel…` → …
=> client: Fix Add Network button state

src/core/corenetwork.cpp, src/core/corenetwork.h, src/core/coresessioneventprocessor.cpp
* Only match on `nickname` for auto-`WHOX`, don't search realname/etc
* Fixes `AutoWho` printing other nicks with matching realname/etc to status buffer
* Avoids relying on server defaults
* Cancel auto-who of nicknames when they quit
* Avoids needlessly filling up `AutoWho` queue with removed users
* Reduces likelihood of getting an unexpected, unhidden result to `WHO` replies
Impact | ★★☆ *2/3* | User-facing, avoids filling server buffer with unexpected commands
Risk | ★☆☆ *1/3* | Possibly wrong `WHO`-extended output, missing `WHO` info
*Thanks to @genius3000 for reporting the `WHOX` issue and finding a solution!*
1. Join Quassel core …
=> core: Fix auto-who nickname handling

src/core/corenetwork.cpp, src/core/corenetwork.h, src/core/coresessioneventprocessor.cpp
* Remove `away-notify` `AutoWho`-on-join hack for non-compliant servers
* Removes workaround for servers not sending `:AWAY :message` when an `/away` user joins channel
* Reduces network traffic
* Results in missing information until servers fix their implementations
* Clean up `AutoWho` comments and variable names
* Use the `name` convention [from RFC 1459](https://tools.ietf.org/html/rfc1459#section-4.5.1 )
* Clarifies that channels and nicknames can be `WHO`'d
Impact | ★★☆ *2/3* | Speedier `AutoWho` behavior, less network traffic to busy servers
Risk | ★★☆ *2/3* | Missing info on servers behind the IRCv3 times
*Thanks to @jwheare for …
=> core: Remove away-notify WHO-on-join hack, cleanup

src/qtui/mainwin.cpp, src/uisupport/settingspage.cpp
Auto-deleting dialogs is a bad idea if we're accessing the instance
after exec(). We could work around this in the affected cases,
however it may be easier and cleaner to create the dialogs on the
stack again, but don't parent them to avoid the crashes we intended
to fix with this commit.
This reverts the previous approach where we would create all dialogs on the
heap with WA_DeleteOnClose attribute, which caused crashes when we tried
to access such a dialog after exec().
=> Fix MainWin dialogs

src/common/CMakeLists.txt, src/common/abstractsignalwatcher.h, src/common/posixsignalwatcher.cpp, src/common/posixsignalwatcher.h, src/common/quassel.cpp, src/common/quassel.h, src/common/windowssignalwatcher.cpp, src/common/windowssignalwatcher.h, src/qtui/monoapplication.cpp, src/qtui/qtuiapplication.cpp
The set of functions we're allowed to safely use in a POSIX signal
handler is very limited, and certainly does not include anything Qt.
While our previous implementation seemingly worked anyway as long as
all it did was quitting the application, we now start seeing issues
when doing a proper shutdown.
Fix this by providing and using PosixSignalWatcher, which uses
socket notification to safely hand over control from the signal
handler to the Qt event loop.
NOTE: This is work-in-progress and needs to be made cross-platform.
=> common: Don't use unsafe functions in the signal handler

src/uisupport/bufferviewfilter.cpp
* Sort buffer views case-insensitively, including network name
* Primarily affects network name; channels/PMs already appear to be correctly sorted
* Still able to rearrange channels/PMs when sorting is disabled
* Doesn't provide control over sorting networks (same as before)
Impact | ★☆☆ *1/3* | User-facing network sorting consistency
Risk | ★☆☆ *1/3* | Network order may change; [workflows might be upset](https://xkcd.com/1172/ )
Quassel sorts most things alphabetically in a case-insensitive manner, including the nickname list.  The network name list should also be sorted case-insensitively to match.
Add three networks, `Alpha`, `beta`, …
=> client: Sort network name case-insensitively

src/uisupport/bufferviewfilter.cpp
* When filtering buffers by string, prioritize relevant results first
* Priorize by exact matches, then matches that start with the string, then all else
* Within these priorities, everything's sorted as before
* Makes it easier to search by exact/starting string
Impact | ★☆☆ *1/3* | User-facing change in buffer filter order
Risk | ★☆☆ *1/3* | Order of buffer filtering (new to 0.13) will change; could be unexpected
It seems more likely to search for a channel/nickname with the starting letters rather than filtering by the middle, as that's how the channel/nickname list is sorted (*when alphabetical sorting is enabled*).  Similarly, an …
=> client: For filtering, prioritize exact, startsWith

src/common/ircuser.cpp, src/common/ircuser.h
IrcUser::setLastAwayMessage() is called by pre-0.13 cores (newer
cores call setLastAwayMessageTime() instead). Fix wrong use of
QDateTime::from[M]SecsSinceEpoch(), which is a static method returning
a new QDateTime instance rather than a modifying setter.
Also fix signatures passing primitive types as const refs.
=> ircuser: Fix setting of away message time by pre-0.13 cores

src/common/bufferviewmanager.h
Two syncable methods where accidentally demoted from being slots,
so adding/removing buffer views would not be synced anymore.
Fix this by making those methods slots again.
=> common: Fix syncing of BufferViewManager

.travis.yml, CMakeLists.txt, cmake/QuasselCompileSettings.cmake, cmake/QuasselInstallDirs.cmake, src/client/clientauthhandler.cpp, src/client/networkmodel.cpp, src/core/coreauthhandler.cpp, src/qtui/settingspages/shortcutsmodel.cpp, src/uisupport/bufferview.cpp, src/uisupport/bufferview.h, src/uisupport/graphicalui.cpp
Increase the warning level on MSVC. Fix some warnings that have been found by this. Add a CMake options to make warnings fatal, and enable in Travis (for Appveyor, we'll need to update the blueprint).
=> Increase warning level on MSVC; fix warnings, make fatal

src/common/serializers/serializers.cpp
Fix a bug where a quint16 would be deserialized into a QVariant
of type Int (instead of UShort). This broke the sync of
autoReconnectRetries in the network settings, because the slot's
signature didn't match the type of the QVariant.
The issue was caused by QVariant not having a constructor for
quint16, thus casting it into an int. Fix this by using
QVariant::fromValue(), which handles the type correctly.
Use the opportunity to remove much of the code duplication in the
deserialization code by providing and using a template function,
avoiding potential other issues with using QVariant's constructor.
=> serializers: Fix quint16 deserialization, remove code duplication

src/main/CMakeLists.txt
The post-build actions for OSX were not conditional on the selected
Quassel variants, so add_custom_command would be added to an undefined
target in that case.
This bug has been there since literally forever; however, CMake < 3.0
silently ignored the custom commands in that case, and thus this
issue was not visible.
With cmake_minimum_required now set to 3.5, the new behavior is
enabled and causes an error at configure time. Fix this by adding
the missing conditions.
=> cmake: Fix OSX post-build if not all targets are requested

CMakeLists.txt, src/common/CMakeLists.txt, src/test/util/CMakeLists.txt
Add a dependency to Boost in the modules that use Boost already,
so Boost headers installed in a non-standard location are found.
=> cmake: Add missing Boost dependency

src/client/networkmodel.cpp
The minimal build requirements we defined for the 0.13 branch don't
support list initialization for QStringList, so replace the two
places where we accidentally slipped that in by the legacy way
of doing things.
=> client: Don't use list initialization for QStringList

src/common/quassel.cpp, src/core/core.cpp, src/core/identserver.cpp
The internal identd is now listening on all adresses, which makes it easier for users to run the core with the required capability and without a proxy. This also makes it possible to run the core in containers, as there incoming packets are never from localhost (but usually somewhere within of 10.0.0.0/8)
Additionally, in case the core has just now been configured from environment, the core would usually ignore all options. This has now been fixed.
=> [master] core: Internal identd listen all, fix config-from-env

src/common/main.cpp, src/core/core.cpp, src/core/identserver.cpp
* Allow specifying internal identd listening addresses, not just local
* Fix `--config-from-environment` first-time setup ignoring other CLI arguments
Impact | ★★☆ *2/3* | Fixes first-time ENV configuration, allows identd without oidentd
Risk | ★☆☆ *1/3* | Opens internal identd, users should be careful
Intrusiveness | ★★☆ *2/3* | New log strings, shouldn't interfere with other pull requests
*All credit to @justJanne including the work backporting - this is just opening the PR and doing a basic test.*
See the [`master` branch pull request #457, "Fixes for identd and config-from-environment"](https://github.com/quassel/quassel/pull/457 ).
**Command**
```
$ ./run-quasselcore.sh --ident-daemon
```
**Outcome**
*Quassel core identd is …
=> [0.13] core: Internal identd listen all, fix config-from-env

src/qtui/inputwidget.ui, src/qtui/mainwin.cpp
*This Pull Request is intended to be merged directly into master. Another pull request with the same fixes for the 0.13 backport branch is available at #462*
The buttons now take the height of the largest element, all elements are now vertically centered.
Starting with commit 66e6d26 the nicklist gets hidden in
setDisconnectedState, but only unhidden in loadLayout.
As loadLayout skips the setVisible(true) if the state is empty, the
actual widget gets never shown, and the nicklist dock remains empty.
This was fixed by moving the setVisible call above the conditional
return.
=> [master] Fix several minor UI issues

src/qtui/mainwin.cpp, src/qtui/ui/inputwidget.ui
*This Pull Request is intended to be merged directly into the 0.13 branch. Another pull request with the same fixes for master is available at #463*
The buttons now take the height of the largest element, all elements are now vertically centered.
Starting with commit 66e6d26 the nicklist gets hidden in
setDisconnectedState, but only unhidden in loadLayout.
As loadLayout skips the setVisible(true) if the state is empty, the
actual widget gets never shown, and the nicklist dock remains empty.
This was fixed by moving the setVisible call above the conditional
return.
=> [0.13] Fix several minor UI issues

src/main/main.cpp
* Don't add quotes to exist exception messages
* When logging exit exceptions, wrap the `QString` in `qPrintable()`
* Removes extra quotes added by the debug logger
Impact | ★☆☆ *1/3* | Small cosmetic change to debug logs
Risk | ★☆☆ *1/3* | Might cause issues with printing exit exception messages
There's a [backport to `0.13` available here](https://github.com/quassel/quassel/pull/471 ).
```
2019-01-27 02:28:52 [Error] Could not open any network interfaces to listen on!
2019-01-27 02:28:52 [Error] "Cannot open port for listening!"
```
```
2019-01-27 02:33:17 [Error] Could not open any network interfaces to listen on!
2019-01-27 02:33:17 …
```
=> common: Don't add quotes to exit exceptions

src/common/main.cpp
* Don't add quotes to exist exception messages
* When logging exit exceptions, wrap the `QString` in `qPrintable()`
* Removes extra quotes added by the debug logger
Impact | ★☆☆ *1/3* | Small cosmetic change to debug logs
Risk | ★☆☆ *1/3* | Might cause issues with printing exit exception messages
This is [applied to `master` here](https://github.com/quassel/quassel/pull/470 ).
```
2019-01-27 02:28:52 [Error] Could not open any network interfaces to listen on!
2019-01-27 02:28:52 [Error] "Cannot open port for listening!"
```
```
2019-01-27 02:33:17 [Error] Could not open any network interfaces to listen on!
2019-01-27 02:33:17 [Error] …
```
=> [0.13] common: Don't add quotes to exit exceptions

src/core/abstractsqlstorage.cpp, src/core/abstractsqlstorage.h, src/core/postgresqlstorage.cpp, src/core/postgresqlstorage.h, src/core/sqlitestorage.cpp, src/core/sqlitestorage.h
* Track last successful upgrade step (`upgrade_###_XXX.sql`) within each schema version
* Store in `schemaupgradestep`, cleared when a schema version upgrade finishes
* Allows resuming interrupted multi-step schema upgrades
* Aids debugging after the fact
* Should not add any additional failure cases
* Update logging to be more explicit about what schema version fails
* Remove redundant `updateSchemaVersion()` call
* Already handled within loop, cleans up after https://github.com/quassel/quassel/commit/f10304a35af0a7a4f8b812e467e69287d358ce7c
Impact | ★★★ *3/3* | Reduces risk of breaking database with interrupted upgrades
Risk | ★★★ *3/3* | Schema steps might not be stored correctly, breaking upgrades
Intrusiveness | ★☆☆ *1/3* | …
=> core: Track upgrade step within each schema version

src/core/abstractsqlstorage.cpp, src/core/abstractsqlstorage.h, src/core/postgresqlstorage.cpp, src/core/postgresqlstorage.h, src/core/sqlitestorage.cpp, src/core/sqlitestorage.h
* Track last successful upgrade step (`upgrade_###_XXX.sql`) within each schema version
* Store in `schemaupgradestep`, cleared when a schema version upgrade finishes
* Allows resuming interrupted multi-step schema upgrades
* Aids debugging after the fact
* Should not add any additional failure cases
* Update logging to be more explicit about what schema version fails
* Remove redundant `updateSchemaVersion()` call
* Already handled within loop, cleans up after https://github.com/quassel/quassel/commit/f10304a35af0a7a4f8b812e467e69287d358ce7c
Impact | ★★★ *3/3* | Reduces risk of breaking database with interrupted upgrades
Risk | ★★★ *3/3* | Schema steps might not be stored correctly, breaking upgrades
Intrusiveness | ★☆☆ *1/3* | …
=> [0.13] core: Track upgrade step within each schema version

src/common/logger.cpp, src/common/logger.h, src/qtui/debuglogdlg.cpp
* Improves Quassel's `--syslog` output
* Removes redundant log level messages, e.g. `[Info]`
* Adds PID
* Deduplicate code for converting LogEntry to printable format
Impact | ★☆☆ *1/3* | Improves log handling for `--syslog`, including systemd
Risk | ★☆☆ *1/3* | Logging might be wrongly formatted or not logged at all
Intrusiveness | ★☆☆ *1/3* | Small changes, shouldn't interfere with other pull requests
*All credit to @vehk for the original work, this is just testing and an additional fix.*
See the [`master` branch pull request #460, "Make output to syslog nicer"](https://github.com/quassel/quassel/pull/460 ).
> Before: `2019-01-11T22:52:27+00:00 hostname info [Info ] Quitting...`
> After: `2019-01-11T16:19:43+00:00 hostname info …
=> [0.13] logger: Make output to syslog nicer

src/core/SQL/PostgreSQL/select_messagesAllNew_filtered.sql, src/core/SQL/PostgreSQL/select_messagesAll_filtered.sql, src/core/SQL/PostgreSQL/select_messagesNewerThan_filtered.sql, src/core/SQL/PostgreSQL/select_messagesNewestK_filtered.sql, src/core/SQL/PostgreSQL/select_messagesRange_filtered.sql, src/core/SQL/SQLite/select_messagesAllNew_filtered.sql, src/core/SQL/SQLite/select_messagesAll_filtered.sql, src/core/SQL/SQLite/select_messagesNewerThan.sql, src/core/SQL/SQLite/select_messagesNewerThan_filtered.sql, src/core/SQL/SQLite/select_messagesNewestK.sql, src/core/SQL/SQLite/select_messagesNewestK_filtered.sql, src/core/SQL/SQLite/select_messagesRange_filtered.sql, src/core/postgresqlstorage.cpp, src/core/sqlitestorage.cpp
* Workaround [Qt 4's `QSqlQuery::bindValue()`](https://doc.qt.io/archives/qt-4.8/qsqlquery.html#bindValue) not replacing multiple placeholders
* When a placeholder appears multiple times, rename the extra placeholders to have unique names
* Adapt `SqliteStorage` and `PostgresqlStorage` to provide extra placeholders as needed
* E.g. `AND (:flags = 0 OR backlog.flags & :flagsDup1 != 0)`
* [Qt 5's `QSqlQuery::bindValue()`](https://doc.qt.io/qt-5/qsqlquery.html#bindValue) handles this correctly (*thankfully*)
* Fixes [issue #1506](https://bugs.quassel-irc.org/issues/1506)
* No need to forward-port to 0.14/`master`, as Qt 4 support has been dropped
* Not required for `0.13.1`, can be postponed to an immediately-following `0.13.2`
* Might reduce risk of breakage before Debian's import freeze as …
=> [0.13] core: Workaround Qt 4 SQL bindValue() duplicates

src/common/logger.cpp, src/common/logger.h, src/qtui/debuglogdlg.cpp
Before: `2019-01-11T22:52:27+00:00 hostname info [Info ] Quitting...`
After:  `2019-01-11T16:19:43+00:00 hostname info quasselcore[4438]: Quitting...`
This patch improves quasselcore's syslog output by adding a program name and instructing the logger to include the process's PID for every message.
Additionally, it removes superfluous log levels in the log message, as syslog is already aware of them.
Potential issues: If you log to a file and syslog at the same time (not sure whether this is possible, didn't check), the log level will not be included in the log file, since the check for _syslogEnabled will override that.
=> Make output to syslog nicer

tests/common/expressionmatchtest.cpp
* Verify `ExpressionMatch` handles invalid regular expressions correctly
* Ensure there's no crash and that this won't regress in future changes
* Matches @justJanne 's [test for Quasseldroid-NG](https://git.kuschku.de/justJanne/QuasselDroid-ng/commit/f1f320782cb0bca3fb7974e7688ce33af19456cf )
Impact | ★☆☆ *1/3* | Further verifies proper operation of `ExpressionMatch`
Risk | ★☆☆ *1/3* | Adds another development-only test
```
[...]/Quassel/quassel-build$ ctest
Test project [...]/Quassel/quassel-build
Start 1: ExpressionMatchTest
1/3 Test #1: ExpressionMatchTest ..............   Passed    0.00 sec
Start 2: FuncHelpersTest
2/3 Test #2: …
```
=> tests: Verify ExpressionMatch with invalid regex

src/core/core.h, src/core/coreauthhandler.cpp, src/core/ldapauthenticator.cpp
This commit attempts to resolve issue #1501; currently, quassel will always attempt to do local authentication, and *then* try LDAP auth. This makes it difficult to migrate a core from local auth to LDAP auth; users who have local passwords can always use those passwords to log in, and there is not a simple way to migrate them to non-local auth.
There is an "authenticator" column in the database for each user, but it is currently only used to stop passwords from being changed for LDAP users. This commit modifies the login flow to first check that database field-- if authenticator is not "Database", we don't try local authentication and proceed directly to non-local authentication.
This is a bit clumsy-- I added a method to the core to look up a user's authenticator by string. But there's …
=> Core: only try local auth if a user has the "database" auth provider set

CMakeLists.txt, cmake/QuasselMacros.cmake
Add an ENABLE_SHARED option, defaults to ON, when set to OFF
quassel_add_module() will build modules as static (does not affect
platforms where modules would be built as static anyway.)
The option name ENABLE_SHARED is frequently used for this purpose in
cmake.
=> cmake: add ENABLE_SHARED option, default ON

CMakeLists.txt, INSTALL
Require Boost 1.54 instead of 1.56.
Tested to compile and work correctly on OpenSUSE Leap 42.3.
Related issue #1510.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
=> lower Boost dep version 1.56 -> 1.54

data/quassel.notifyrc
This allows the new notification KCM to identify Quassel as an application
=> Add DesktopEntry to notifyrc

src/qtui/knotificationbackend.cpp
Lets the notification server load an appropriate crisp pixmap depending on the size it wants to display it at
=> Send icon name instead of pixmap

src/common/quassel.cpp, src/qtui/mainwin.cpp
* adds new --account option
* if an account id is specified, connects to that account instead of asking or using any other defaults
| - | - | - |
| Impact | ★☆☆  _1/3_ | Only usable by power users, won’t affect common users at all |
| Risk | ★★☆  _2/3_ | Touches autoconnect code, might break that |
=> Allow selecting the core account to connect to from CLI

src/common/util.cpp, tests/common/CMakeLists.txt, tests/common/utiltest.cpp
* Previously, a convoluted workaround using deprecated functionality was used to ensure we would format all types of QDateTime objects correctly
* A new workaround has been found which ensures this works reliably without using deprecated functionality
| - | - | - |
| Impact | ★☆☆  _1/3_ | Does not have any noticeable changes, fixes a compiler warning |
| Risk | ★☆☆  _1/3_ | Touches time code, but has unit tests |
Currently our builds for windows fail because of a compiler warning about using deprecated functionality in our previous workaround for time formatting.  
In the search for a way to fix this, this simpler workaround for the same issue has been found, and works reliably.
To ensure …
=> Simplify the time formatting used in formatDateTimeToISO

src/common/quassel.cpp, src/core/CMakeLists.txt, src/core/core.cpp, src/core/core.h, src/core/coreauthhandler.cpp, src/core/corenetwork.cpp, src/core/corenetwork.h, src/core/coresession.cpp, src/core/coresession.h, src/core/metricsserver.cpp, src/core/metricsserver.h, src/core/sslserver.cpp, src/core/sslserver.h
* Adds an HTTP-based metrics API to expose certain metrics for Prometheus
* Adds an HTTP-based healthz API to allow container systems to determine that the core has started
| - | - | - |
| Impact | ★☆☆  _1/3_ | Allows easier monitoring for use in automated deployments |
| Risk | ★☆☆  _1/3_ | Does not touch any critical code |
| Intrusiveness | ★☆☆  _1/3_ | Changes localized to few rarely-touched classes, shouldn't interfere with other pull requests |
Exposing metrics allows monitoring of these, which also allows automated alerts in case something unexpected happens (e.g. a user on a shared core connecting to hundreds of networks, or having thousands of clients connected).
Additionally, this opens the way for including more metrics, such as exposing the …
=> Implement a metrics daemon to expose Prometheus metrics

src/qtui/knotificationbackend.cpp
This makes the entire notification popup clickable.
Also, mark the text for translation.
I couldn't find a minimum version requirement of KDE Frameworks for Quassel
but this method was added in Frameworks 5.32 in Early 2017 and supported
since Plasma 5.10. For older versions a regular button should be shown as is
since they will just not know what "default" means and take that as a regular
button action ID.
=> Set default action on notification

CMakeLists.txt, cmake/QuasselCompileSettings.cmake, cmake/QuasselMacros.cmake
Some minor changes to allow building easily on MSYS2:
- don't check for snorenotify on MSYS2 because it segfaults on startup
- don't use -fstack-protector-strong (libssp) on MinGW because it
currently causes segfaults during static initialization
https://sourceforge.net/p/mingw-w64/bugs/755/
- build libraries as static on Windows, the comments indicate that this
was the intention, but the check was not implemented
- use the `cat` command to read files when using the 'MSYS Makefiles'
generator, and not the cmd.exe `type` command
Tested to build correctly on MSYS2 with both the 'MSYS Makefiles'
generator and the Ninja generator using a native ninja.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
=> cmake: fix build on MSYS2

src/main/monoapplication.cpp, src/qtui/qtuiapplication.cpp
The XCB platform plugin defaults the WM class to the executable name,
which already matches our desktop file name. Unfortunately, the Wayland
platform plugin prepends the inverted organization domain, resulting in
an app ID of "org.quassel-irc.quasselclient", thus breaking the
association.
Set the desktop file name explicitly so the Wayland platform doesn't get
confused.
=> qtui: Set desktop file name

CMakeLists.txt, src/client/buffermodel.cpp, src/client/clientbacklogmanager.cpp, src/client/messagefilter.cpp, src/client/messagemodel.cpp, src/client/networkmodel.cpp, src/client/treemodel.cpp, src/core/abstractsqlstorage.cpp, src/core/coresessioneventprocessor.cpp, src/core/oidentdconfiggenerator.cpp, src/core/sqlitestorage.cpp, src/qtui/chatitem.cpp, src/qtui/chatlinemodelitem.cpp, src/qtui/chatview.cpp, src/qtui/chatviewsearchcontroller.cpp, src/qtui/nicklistwidget.cpp, src/qtui/settingspages/appearancesettingspage.cpp, src/qtui/settingspages/bufferviewsettingspage.cpp, src/qtui/settingspages/corehighlightsettingspage.cpp, src/qtui/settingspages/highlightsettingspage.cpp, src/qtui/settingspages/itemviewsettingspage.cpp, src/qtui/settingspages/itemviewsettingspage.h, src/uisupport/abstractbuffercontainer.cpp, src/uisupport/bufferview.cpp, src/uisupport/nickviewfilter.cpp, src/uisupport/styledlabel.cpp, src/uisupport/uistyle.cpp, src/uisupport/uistyle.h
* removes and updates lots of outdated and deprecated code
* fixes compiler warnings on Qt 5.13
| - | - | - |
| Impact | ★☆☆  _1/3_ | Makes code more robust for future Qt versions |
| Risk | ★☆☆  _1/3_ | Code is not functionally different in any way |
| Intrusiveness | ★★★  _3/3_ | Changes throughout the whole codebase |
Our builds on Qt 5.13, as used on AppVeyor, fail currently entirely, leading to unreliable CI results. Additionally, using long-deprecated code is advised against.
This PR removes and replaces all deprecated code, making the codebase more robust for the future, as well as fixing compiler warnings
=> Fix deprecation warnings

po/CMakeLists.txt
A mismatch in the stamp file name for syncing translations caused
the sync to be run for every make. Fix the naming so we don't
re-run the syncing needlessly.
=> cmake: Don't needlessly sync translations

src/common/dccconfig.cpp, src/common/dccconfig.h, src/common/ignorelistmanager.cpp, src/core/abstractsqlstorage.cpp, src/core/abstractsqlstorage.h, src/core/core.h, src/core/coreauthhandler.cpp, src/core/corebacklogmanager.cpp, src/core/corebuffersyncer.cpp, src/core/coreidentity.cpp, src/core/coreidentity.h, src/core/corenetwork.cpp, src/core/coresession.cpp, src/core/coresession.h, src/core/postgresqlstorage.cpp, src/core/postgresqlstorage.h, src/core/sqlitestorage.cpp, src/core/sqlitestorage.h, src/core/storage.h, src/qtui/chatline.cpp, src/qtui/chatline.h
* Replace Qt module includes by class ones
* Use `std::vector` instead of `QList` in the storage API and related classes
* Clean up CoreIdentity
* Avoid some warnings new in GCC 9
=> Assorted cleanups and modernization

.travis.yml
Quassel builds for ubuntu cosmic, disco and eoan fail if running in docker on a xenial host
Ubuntu cosmic, disco and eoan use Qt 5.11 and 5.12 respectively, which makes use of the new syscall statx (introduced in Qt 5.10, bionic and xenial are still on 5.9 and 5.5 respectively).
Ubuntu xenial supports statx, as does docker, which is up to date on these distros. but sadly libseccomp, which is used to filter syscalls, is too old on these distros.
So code sees that statx is available, tries to run it, and it returns with an error, which is considered file not existing
Update the host for our build to at least bionic, where this issue doesn’t exist
=> Fix builds for cosmic/disco/eoan

src/common/quassel.cpp
I tried QStandardPaths but the application name is not quassel but "Quassel Project" ....
=> Use correct data Path on Windows

src/core/identserver.cpp, src/core/identserver.h
* Adds debug output for identd
* Improves compatibility and performance, cleans up identd response code
* Improves compatibility with certain networks
| - | - | - |
| Impact | ★☆☆  _1/3_ | Fixes identd on few smaller networks |
| Risk | ★☆☆  _1/3_ | Only affects edge cases where other software misinterprets the standard |
Currently, our internal identd fails *sometimes* when connecting to irc.darkscience.net. This has been fixed by giving the other side some time to handle the response before closing the socket, which previously caused issues with outdated IRCds on FreeBSD.
We didn’t entirely implement the spec strictly with this solution as many other projects only base their implementations …
=> Identd bugfixes and improvements

src/common/ircchannel.cpp, src/common/ircuser.cpp, src/common/ircuser.h
* Only transmit one message to part a channel instead of two per each user
| - | - | - |
| Impact | ★☆☆  _1/3_ | Reduces protocol spam, reducing the perceived latency of some operations |
| Risk | ★☆☆  _1/3_ | Could trigger bugs in older clients |
| Intrusiveness | ★☆☆  _1/3_ | Changes localized to few rarely-touched classes, shouldn't interfere with other pull requests |
When we leave a channel, we currently not only transmit the protocol message that we have left, but also a part (and potentially a quit) message for each user in that channel. Clients can synthesize these themselves, though, and already do.
As result, these messages get discarded by clients and only serve to fill the connection with spam.
=> Fix protocol spam on part/quit/disconnect

src/uisupport/multilineedit.cpp
Currently, if an unterminated mIRC code is pasted into Quassel, trying to
go through input line history will cause a deadlock.  This breaks the loop
at the cost of possibly mangling the formatting of the line somewhat.
This is seen as more acceptable than locking up, and the line is invalid
anyway.
Reproducer:
```sh
printf '\00303,08HONK' | xclip -selection clipboard
```
Paste into Quassel, send, press Up arrow key.
Bug originally found by @sroracle, reported to Adélie Linux, patched by
yours truly.
=> multilineedit: handle unterminated mIRC codes

src/core/metricsserver.cpp, src/core/metricsserver.h
* Remove unused raw login metric
* We won't ever have more than 4 billion sessions at a time per user, use int32_t instead of int64_t
| - | - | - |
| Impact | ★☆☆  _1/3_ | Removes a minor unnecessary metric, fixes a situation that’ll never happen but makes it cleaner |
| Risk | ★☆☆  _1/3_ | Might break existing prometheus dashboards for quassel |
| Intrusiveness | ★☆☆  _1/3_ | Changes localized to one class |
Just a tiny cleanup
=> Minor cleanup of metrics server

src/common/CMakeLists.txt, src/common/authhandler.h, src/common/ircdecoder.cpp, src/common/ircdecoder.h, src/common/protocol.h, src/common/protocols/legacy/legacypeer.cpp, src/common/proxyline.cpp, src/common/proxyline.h, src/common/quassel.cpp, src/common/remotepeer.cpp, src/common/remotepeer.h, src/core/core.cpp, src/core/coreauthhandler.cpp
* Adds support for the HAProxy proxy protocol to the client-side auth handler
* Uses the forwarded IP information in the client list
* Adds a CLI option to specify which IP ranges are trusted proxies
| - | - | - |
| Impact | ★☆☆  _1/3_ | Allows deploying Quassel behind load balancers |
| Risk | ★★☆  _2/3_ | Affects main protocol initialization code |
| Intrusiveness | ★☆☆  _1/3_ | Changes localized to few rarely-touched classes, shouldn't interfere with other pull requests |
In cloud deployments, it’s common to deploy services behind load balancers or proxies. In such situations, it’s useful to still be able to show the original IP of the request.
Now that we show clients by IP in the client list, support for this protocol is useful.
=> Implement support for the HAProxy proxy protocol

src/common/buffersyncer.cpp, src/common/buffersyncer.h, src/core/SQL/PostgreSQL/select_buffer_last_messages.sql, src/core/SQL/SQLite/select_buffer_last_messages.sql, src/core/core.h, src/core/corebuffersyncer.cpp, src/core/postgresqlstorage.cpp, src/core/postgresqlstorage.h, src/core/sqlitestorage.cpp, src/core/sqlitestorage.h, src/core/storage.h
* Fixes an issue where permanently merged buffers had wrong buffer activities / highlight counts
* Syncs the last message id per buffer via the buffersyncer
| - | - | - |
| Impact | ★☆☆  _1/3_ | Fixes slightly wrong activity/highlight displays and allows quasseldroid to provide new features |
| Risk | ★☆☆  _1/3_ | Does not touch any critical code |
In the future, we plan to resume chat wherever the user was in quasseldroid, also allowing users to jump to arbitrary points in the history (e.g. for fast-scrolling to a certain day, for jumping to search results or notifications).
To allow this, not only do we have to have bidirectional backlog requesting (which will come soon), but we also have to …
=> Sync last msgid

src/core/corenetwork.cpp, src/core/corenetwork.h
* Fix rare wrong messages for capability negotiation
* Distinguish between `No capabilities available` and not supporting what's available
* For `/CAP LS`, display the current status of capabilities, available and enabled
* Clarify name of `capNegotiationInProgress()`
* Actually refers to whether or not any capabilities are pending negotiation
*Thanks to `Koragg` on `freenode` for reporting this!*
Impact | ★★☆ *2/3* | Fixes rare user-facing misinformation, easier IRCv3 debugging
Risk | ★☆☆ *1/3* | Information messages may be inaccurate
Intrusiveness | ★☆☆ *1/3* | Small, new strings, shouldn't interfere with other pull requests
```
[1:58:23 am] * Requesting capability list...
[1:58:23 am] * Ready to negotiate (found: cap-notify, …
```
=> core: Fix capability messages for repeat CAP LS

src/common/aliasmanager.cpp, src/common/aliasmanager.h, src/common/highlightrulemanager.cpp, src/common/highlightrulemanager.h, src/common/ignorelistmanager.cpp, src/common/ignorelistmanager.h, src/common/syncableobject.cpp, src/common/syncableobject.h, src/core/postgresqlstorage.h, src/core/sqlitestorage.h, src/core/storage.h, src/qtui/settingspages/aliasesmodel.cpp, src/qtui/settingspages/aliasesmodel.h, src/qtui/settingspages/corehighlightsettingspage.cpp, src/qtui/settingspages/dccsettingspage.cpp, src/qtui/settingspages/ignorelistmodel.cpp, src/qtui/settingspages/ignorelistmodel.h
QObjects are non-copyable for good reasons. SyncableObject, although
deriving from QObject, was made sort-of copyable by adding custom copy
ctor and copy assignment operator that did not make a full copy of the
underlying QObject, but just copied (most) properties. Several classes
deriving from SyncableObject then implemented their own versions of
those special member functions on top of that. This was not only
rather unexpected and intransparent behavior due to the incomplete
copy functionality, but also a most fragile hack since one had to
remember to update those functions when adding or modifying
properties.
In addition, newer compilers apply a somewhat stricter interpretation
of the C++ standard, basically enforcing the Rule of Three by omitting
implicit generation of copy ctor …
=> common: Make SyncableObject non-copyable

src/common/ircchannel.cpp, src/common/ircuser.cpp, src/common/ircuser.h
* Moves functionality to an internal function
* Restores original sync slots
| - | - | - |
| Impact | ★★★  _3/3_ | Fixes functionality with older clients |
| Risk | ☆☆☆  _0/3_ | Just fixes existing functionality |
| Intrusiveness | ★☆☆  _1/3_ | Changes localized to few rarely-touched classes, shouldn't interfere with other pull requests |
The previous PR-495 broke functionality on several older clients, which this restores.
=> [Followup PR-495] Fixes backwards compatibility issues

data/networks.ini
Mozilla IRC has shut down this month. Mozilla moved their chat services to matrix. I am removing it from the default preset now.
=> Removed mozilla IRC network from networks.ini

.github/workflows/main.yml
Check if expected artifacts have been created for every workflow run,
not only for tagged commits. While this is just a rudimentary
sanity check, it would at least cause a CI failure if one of the
build jobs didn't produce artifacts for some reason.
A nice side effect is that unlike the former create-release job,
the new post-build job is not completely skipped for non-tagged
commits, and thus shows up as successful for every good CI run
(even though the individual steps required for creating a draft
release are skipped, of course).
This causes the GitHub UI to automatically collapse the (giant)
list of checks after they are all complete.
=> ci: Add sanity check for artifacts to post-build job

src/common/identity.cpp, src/qtui/settingspages/identityeditwidget.ui
* Enable `Away on Detach` by default for new identities
* Existing identities will stay as they are
* Matches IRCCloud behavior (not sure about ZNC), other chat networks
* Client-side change; core has no impact
Impact | ★☆☆ *1/3* | User-facing, helps communicate whether someone may respond
Risk | ★★☆ *2/3* | Privacy change, default now reveals whether a client is connected
Intrusiveness | ★☆☆ *1/3* | UI/defaults changes, shouldn't interfere with other pull requests
Most modern chat networks automatically manage presence to some manner.  IRCCloud defaults to setting `Auto-away` on (*Set your away status when you leave the page*), Discord, Steam, and several Jabber/XMPP clients (Conversations, Gajim, Pidgin) set presence based on …
=> common: Default to Away on Detach for new identities

.github/workflows/main.yml
Currently, OSX packaging is unreliable due to a race condition in the
scripts, sporadically leading to a missing QuasselCore package. A
proper fix would require a modernization of the packaging process.
Mark the artifact sanity check non-fatal for now, until a proper
solution can be implemented.
=> ci: Make artifact sanity checks non-fatal for now

src/common/message.cpp, src/common/message.h, src/core/SQL/PostgreSQL/select_buffer_bufferactivity.sql, src/core/SQL/PostgreSQL/select_buffer_highlightcount.sql, src/core/SQL/SQLite/select_buffer_bufferactivity.sql, src/core/SQL/SQLite/select_buffer_highlightcount.sql, src/core/corebuffersyncer.h, src/core/coresession.cpp
* Mark messages as `Ignored` if matched by an ignore rule
* Useful for dynamic ignores (`SoftStrictness`); permanent (`HardStrictness`) are dropped
* Simple clients/bots can filter out ignored messages without implementing `ExpressionMatch`
* Not used for full clients as they reveal hidden messages when disabling specific ignore rules
* Exclude messages that match an ignore rule when updating `bufferActivity` and `highlightCount`
* Fixes [issue #1511, appearance of new activity/highlights from ignored messages](https://bugs.quassel-irc.org/issues/1511 )
* No client changes needed
* Clean up an old comment
Impact | ★★☆ *2/3* | User-facing, avoids common complaint of misleading activity/highlights
Risk | ★★☆ *2/3* | Protocol-visible …
=> common: Exclude ignored messages in buffer activity

src/client/clientsettings.cpp, src/qtui/mainwin.cpp, src/qtui/settingspages/corehighlightsettingspage.cpp, src/qtui/settingspages/corehighlightsettingspage.h, src/qtui/settingspages/highlightsettingspage.cpp, src/qtui/settingspages/highlightsettingspage.ui
* Disable local nickname highlights by default
* Works around core-side highlight ignores being overridden by local highlights
* Quassel 0.13 with core-side highlights came out 1.5 years ago
* Deemphasize local highlights
* Rename `Local Highlights` → `Legacy Highlights` for core + client setups
* Rename `Remote Highlights` → `Highlights` and place it first in settings
* Make `Import Legacy` import nickname highlight settings, offer to remove old rules
* After 0.14/stable, Quassel should disable client highlights when core highlights exist
Impact | ★★☆ *2/3* | User-facing clarity, reduces highlight annoyances
Risk | ★★☆ *2/3* | Changes highlight rule matching behavior, possible confusion
Intrusiveness | ★★☆ *2/3* | UI, string …
=> client: Deemphasize local highlights, fix ignores

src/common/ircuser.cpp
* Fix `IrcUser::quitInternal()` so it calls `IrcUser::quit()` in protocol
* Addresses nicknames remaining visible in `Nicks` list and buffers after `/quit`
* Finishes the [fix in a previous commit](https://github.com/quassel/quassel/commit/7298446b3e86140c4bbbfe7aeeb959c16c53363c#diff-ddb895c77a2bfda29c64344f593102daR323-R339 ) - that commit unintentionally changed the protocol
* Affects old and new clients, only core needs upgraded
Impact | ★★★ *3/3* | User-facing, fixes nickname quits broken for old and new clients
Risk | ★★☆ *2/3* | Protocol change could break other things, but it's already broken
Intrusiveness | ★☆☆ *1/3* | Minimal code changes, shouldn't interfere with other pull requests
*Thanks to `ephemer0l_` on …
=> common: Fix IrcUser::quitInternal() not syncing quit()

src/client/treemodel.cpp, src/qtui/nicklistwidget.cpp, src/uisupport/abstractbuffercontainer.cpp, src/uisupport/bufferview.cpp, src/uisupport/nickviewfilter.cpp
* Handle invalid `QAbstractItemModel` when switching buffers and elsewhere
* Fixes [issue #1583, "Regression in "Mouse wheel changes selected chat" causing crash"](https://bugs.quassel-irc.org/issues/1583 )
* Regression caused by [commit "Replace deprecated QModelIndex::child with QAbstractItemModel::index"](https://github.com/quassel/quassel/commit/a453c963cf1872e14c83adf1d40a31821c166805 )
* Qt's documentation [only indirectly warned of this](https://doc.qt.io/qt-5/qmodelindex-obsolete.html ), issue is easy to overlook
Impact | ★★★ *3/3* | User-facing crash fix when using hotkeys/shortcuts to switch buffers
Risk | ★☆☆ *1/3* | Return to original code path; possible unexpected behavior or incomplete fix
Intrusiveness | ★☆☆ *1/3* | …
=> client: Fix crash on switching buffers with no buffer selected

src/client/backlogrequester.cpp, src/client/backlogrequester.h, src/client/backlogsettings.cpp, src/client/backlogsettings.h, src/client/clientbacklogmanager.cpp, src/client/messagemodel.cpp, src/qtui/bufferwidget.cpp, src/qtui/bufferwidget.h, src/qtui/chatview.cpp, src/qtui/chatview.h, src/qtui/settingspages/backlogsettingspage.cpp, src/qtui/settingspages/backlogsettingspage.ui, src/qtui/settingspages/chatmonitorsettingspage.cpp, src/qtui/settingspages/chatmonitorsettingspage.h, src/qtui/settingspages/chatmonitorsettingspage.ui
* Fix dynamic backlog requests with 0 initial backlog fetched
* Fallback to fetching newest messages when none exist in a buffer
* Try to ensure backlog is available when showing a buffer
* Fetch as if scrolling, unless the scrollbar is visible
* Default enabled, can be disabled
* Fetched messages might be filtered out; Quassel had this issue before (just scroll more)
* Add `AsNeededBacklogRequester`: fixed backlog for legacy, no backlog for `0.13.0`+
* Modern cores with `Feature::BufferActivitySync` know if activity happened without client fetching
* Should speed up logging in
* Clients connecting to legacy cores behave as `FixedBacklogRequester`
* Breaks `Show messages from backlog` Chat Monitor feature, warnings added to UI
* Default enabled, can be changed to other backlog requester …
=> client: Only fetch backlog when needed, fixup zero backlog

src/core/coreuserinputhandler.cpp
Provide information about available encryption modes and prefixes in /setkey's usage output.
=> Improve setkey usage output

.github/workflows/main.yml, scripts/build/macosx_makePackage.sh
* Workaround macOS packaging out of space errors
* Allow `hdiutil` to automatically determine size
* After [171 tests](https://github.com/digitalcircuit/quassel/actions?query=branch%3Afix-macos-hdiutil-size ), only [3 failed runs](https://github.com/digitalcircuit/quassel/actions?query=branch%3Afix-macos-hdiutil-size+is%3Afailure ) = 98% success
* Make the macOS packaging properly error when commands fail
* Re-enable requirement for macOS build success
Impact | ★☆☆ *1/3* | Developer-facing polish, ensures macOS builds keep working
Risk | ★☆☆ *1/3* | Possible unrelated intermittent build failures
* [171 …
=> ci: Workaround macOS hdiutil out of space errors

src/qtui/aboutdlg.ui, src/qtui/coreinfodlg.ui, src/qtui/coresessionwidget.ui
* Allow opening version links in `Core Info...`
* Follows precedent set by `About` dialog
* Assumes already-authenticated clients/cores won't specify deceptive links
* Add keyboard access to version links
* For `About` dialog, follows the behavior of other links
* For `Core Info...` dialog, ensures keyboard access is feasible
* Introduces more tab stops
Impact | ★☆☆ *1/3* | Minor user-facing ability to open links like expected
Risk | ★☆☆ *1/3* | Malicious authenticated Quassel cores/clients could set phishing links
1.  Start Quassel client
2.  Connect to a Quassel core 0.13.0 or newer
3.  Open `Help` → `About Quassel`
4.  Try using …
=> client: Allow opening commit links in Core Info, add keyboard access

src/qtui/settingspages/networkssettingspage.cpp
* Check for non-existent identity in `Networks` settings
* Fixes crash when identity is deleted or non-existent
* Ported from [patch provided by `kater` in issue #1409](https://bugs.quassel-irc.org/issues/1409 )
Impact | ★★☆ *2/3* | Fixes confusing crash after canceling setup wizard
Risk | ★☆☆ *1/3* | Invalid identity could expose crashes/bugs elsewhere
*I'm not sure how to properly provide credit to `kater`; if they notice this and request different attribution, I'll happily fix it!*
1.  Clear the configuration for Quassel monolithic
2.  Start Quassel monolithic
3.  Cancel the setup wizard (before creating any identity)
4.  Go to …
=> client: Fix Networks settings crash on missing network identity

.github/workflows/main.yml, scripts/build/Info.plist, scripts/build/macosx_DeployApp.py, scripts/build/macosx_makePackage.sh, scripts/build/macosx_makebundle.py, scripts/build/macosx_qt.py
* Specify macOS `LSMinimumSystemVersion` inside `Info.plist`
* Minimum version automatically set [by Qt requirements, `QMAKE_MACOSX_DEPLOYMENT_TARGET`](https://doc.qt.io/qt-5/macos.html#supported-versions )
* Older macOS versions show a clear "OS too old" compatibility warning instead of a crash
* Switch to `HFS+` from `APFS` for the `.dmg` app bundle
* Enables older (pre-10.13) macOS versions to read and check minimum OS version
* Follows [what the Qt `macdeployqt` tool does](https://doc.qt.io/qt-5/macos-deployment.html#the-mac-deployment-tool )
* After [252 tests](https://github.com/digitalcircuit/quassel/actions?query=branch%3Aft-macos-warn-oldver-tests ), only [6 failed tests with 2 being unrelated](https://github.com/digitalcircuit/quassel/actions?query=branch%3Aft-macos-warn-oldver-t …
=> build: Set macOS minimum version to what Qt supports, fix slow CI

src/qtui/topicwidget.cpp
Without this change, it's almost impossible to edit the topic with the
topic widget in busy channels because every message would trigger the
dataChanged signal which would reset the topic and switch the topic
widget out of editing mode.
Fixes #1485.
=> Keep editing topic while someone talks

src/qtui/settingspages/networkssettingspage.cpp, src/qtui/settingspages/networkssettingspage.h, src/qtui/settingspages/networkssettingspage.ui
* Group the SASL EXTERNAL note within the `Use SASL Authentication` box
* Clarifies that `Use SASL` must be checked for SASL EXTERNAL to be used
* Ties the use of SASL EXTERNAL with the SASL availability line
* Check for `sasl=EXTERNAL` support when SASL EXTERNAL is used
* Avoids misleading message that SASL is supported when only `sasl=PLAIN` is available
* Update `Details...` dialog text
* SASL v3.1 may still mislead, phrase details to account for this
Impact | ★☆☆ *1/3* | User-facing clarity for uncommon feature, reduces SASL confusion
Risk | ★☆☆ *1/3* | May make SSL cert appear to not apply for NickServ cert login
Intrusiveness | ★★☆ *2/3* | UI, string changes, may interfere with other PRs
Quassel only negotiates `SASL …
=> client: Group SASL EXTERNAL under Use SASL Auth, test right cap

README.md
* Add [nightly.link](https://nightly.link/ ) download URLs to `README.md`
* Allows downloading Windows and macOS automated builds without signing into GitHub!
* Works around [this issue with GitHub Actions](https://github.com/actions/upload-artifact/issues/51 )
* No special setup required, but strongly recommended to [grant access to the GitHub app](https://github.com/apps/nightly-link ) to avoid API rate limits
Impact | ★☆☆ *1/3* | Developer-facing polish, makes CI downloads easier
Risk | ★☆☆ *1/3* | Links to third-party service, easily reverted
Intrusiveness | ★☆☆ *1/3* | Only changes `README.md`, shouldn't interfere with other pull requests
*Note: Looking at [the branch …
=> docs: Add nightly.link CI download URLs to README

.github/workflows/main.yml
With the introduction of Qt6 to homebrew, the install location of Qt5
has changed from /usr/local/opt/qt to the version-specific .../opt/qt@5.
Adapt CMAKE_PREFIX_PATH accordingly. No longer hardcode the brew
prefix. Also use the recommended, versioned package name "qt@5" instead
of the "qt5" alias.
=> ci: Find Qt5 again on macOS

src/common/ircdecoder.cpp, tests/common/ircdecodertest.cpp, tests/common/ircencodertest.cpp
* Split tag names into at most 2 elements
* Split by the last /, not the first /
| - | - | - |
| Impact | ★☆☆  _1/3_ | Fixes handling of potential future extensions to IRCv3 |
| Risk | ★★☆  _2/3_ | Touches the main IRC parser, but is fully covered by tests |
IRCv3 currently does not specify (or recommend specifying) any tag names which would contain multiple slashes, but IRCv3 does recommend clients should gracefully handle any possible tag, ideally treating it as opaque string.
We’d like to avoid that, but also want to ensure even after a roundtrip through our core, tags we don’t support are still in identical condition.
=> [PR-561] Add support for weird tag names, per the spec.

src/client/clientauthhandler.cpp, src/client/execwrapper.cpp, src/client/treemodel.cpp, src/client/treemodel.h, src/core/postgresqlstorage.cpp, src/core/sqlitestorage.cpp, src/core/sslserver.cpp, src/qtui/ircconnectionwizard.h, src/qtui/mainwin.cpp, src/qtui/nicklistwidget.cpp, src/qtui/sslinfodlg.cpp, src/qtui/verticaldock.h, src/uisupport/bufferview.cpp
* Use QSslConfiguration instead of modifying QSslSocket directly
* Use default constructors instead of nullptr for empty QFlags
| - | - | - |
| Impact | ★☆☆  _1/3_ | Will only have an effect after Qt6 |
| Risk | ★☆☆  _1/3_ | Does not touch any critical code |
| Intrusiveness | ★☆☆  _1/3_ | Changes localized to a few classes
Currently our builds cause [Qt warnings](https://git.kuschku.de/justJanne/quassel-docker/-/jobs/2075#L452) about deprecated functionality.
=> [PR-559] Resolve Deprecation warnings in newer Qt versions

src/qtui/mainwin.cpp
Without the parent correctly set, wayland cannot know it's a child of quassel and management is hazardeous.
=> Fix parents for all dialog windows

cmake/QuasselCompileSettings.cmake, src/client/messagefilter.cpp
Recently, MSVC introduced a new warning C5240 that apparently refers
to standard-compliant ordering of attributes and decl-specifies.
Unfortunately, this warning is triggered by Qt headers, in particular:
C:\CraftMaster\windows-msvc2019_64-cl\include\qt5\QtGui/qcolor.h(233):
warning C5240: 'nodiscard': attribute is ignored in this syntactic position
Since we cannot fix this ourselves, make the warning non-fatal for now.
This fixes our CI failing with the new MSVC version.
Reenable C4244, which is no longer triggered by Quassel code, and add
some reasoning for the remaining warnings.
Fix an issue in MessageFilter that was discovered by disabling warnings
for testing.
=> ci: Adapt warning configuration to new release of MSVC 19

src/client/clientuserinputhandler.cpp
If user type `/join` on a channel without name it will take the name of the current channel
=> Join current channel if no name is given

README.md, data/networks.ini, src/qtui/aboutdlg.cpp
As some folks may be aware, there have been some recent issues that have come to light regarding the ownership and management of Freenode. As a result of this, the entire volunteer staff of Freenode has resigned.
Many projects are packing up and moving to Libera, which is a new IRC network founded by the previous staff of Freenode.
This PR makes the following changes:
* Removes Freenode as the "Default" network. This means that new installations of Quassel will no longer automatically connect to Freenode, unless the user specifically adds Freenode as a network.
* Removes #quassel from "DefaultChannels" under Freenode. This means that new installations of Quassel will no longer join the #quassel channel on Freenode.
* Adds Libera Chat as a new IRC network, and specifies it as the "Default" …
=> Change default IRC network to Libera Chat

src/core/sslserver.cpp
As mentioned in [#1728](https://bugs.quassel-irc.org/issues/1728), cores launched with the `--require-ssl` flag, but no SSL/TLS certificate available (because the file does not exist, permissions are set incorrectly, the file does not contain a certificate, etc) will effectively be put into a plaintext-only mode, with little more than a small warning on the console to the user. Clients connecting to the core will be given the standard "Unencrypted Connection" warning.
This patch fixes that issue, requiring that cores launched with `--require-ssl` will successfully load a certificate before starting. If the certificate fails to load for any reason during startup, an exception is thrown and the core quits.
Thanks to @relrod for the help on this one.
=> core: Error out when --require-ssl is specified, but no cert can be loaded

README.md
* Add back the `README.md` webchat link now that Libera Chat has an option
* Follow up to [changing the official IRC channel](https://github.com/quassel/quassel/commit/322bec12418ab267d7b770ec90465a1a1034b17d)
* Makes it easier for folks having trouble connecting
Impact | ★☆☆ *1/3* | More convenient way to get help with Quassel
Risk | ★☆☆ *1/3* | Links to third-party service, easily reverted
Intrusiveness | ★☆☆ *1/3* | Only changes `README.md`, shouldn't interfere with other pull requests
*Note: Looking at [the branch directly](https://github.com/digitalcircuit/quassel/blob/fix-docs-webchat-again/README.md ) may be easier than using GitHub's pull request difference view.*
Quassel's moved official presence to Libera Chat, but for …
=> docs: Add back webchat link after Libera migration

src/common/expressionmatch.cpp, tests/common/expressionmatchtest.cpp
* Enable [Unicode-aware QRegularExpression](https://doc.qt.io/qt-5/qregularexpression.html#unicode-properties-support )
* Avoids spam highlights like `V` in `XYZ M°VəD to TOTALLY.REAL.CHAT`
* Expands character classes (`\w`, `\d`, etc) to handle Unicode
* Affects existing highlight rules
*Thanks to @deviant for writing the commit!  I merely added the unit tests.  Thanks to `oprypin` for finding the Qt documentation and such, too.*
Impact | ★★☆ *2/3* | Makes it easier to manage Unicode-based spam
Risk | ★☆☆ *1/3* | Impacts nickname highlights, regex rules in Unicode situations
With the recent waves of spam like `/︕\ THІЅ ᏟHΑΝΝᎬL ዘAS МOVED …
=> common: Make regular expressions Unicode-aware

icons/CMakeLists.txt
The `/usr/share/pixmaps` location is considered a legacy location for application icons; since the application icons are already installed in the global XDG hicolor theme, then simply stop installing the 48px one in the legacy pixmaps location.
=> pics: stop installing app icon in pixmaps location

src/common/ignorelistmanager.cpp
* Strip IRC format codes from message for ignores that match message contents
* Simplifies ignoring rainbow-messages, consistent with highlight rules
* Not possible to match specific format patterns, may break complex existing ignores
Impact | ★★☆ *2/3* | Makes it easier to set ignore rules for rainbow spam
Risk | ★★☆ *2/3* | Removes the ability to set format-specific ignore rules
* Pros
* Easier to set ignore rules for rainbow-messages or other format spam
* Consistent with highlight rules/highlight ignore rules
* Cons
* Not possible to ignore messages matching a specific format pattern
* Breaks existing ignores written to handle …
=> common: strip format codes for Message ignores

.github/workflows/main.yml
* [Schedule a monthly CI build](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events ) to catch regressions in build system
* Helps during periods of low commit activity
* Would have (eventually) [caught the recent macOS CI failure](https://github.com/quassel/quassel/commit/7064a9e9b8aec31aca5ac88b4a5190a50dfc84c7 )
* Scheduled for [off-peak hour `13:37` on 14th](https://crontab.guru/#37_13_14_*_*) to help reduce load
* Keeps Quassel CI download artifacts available ([avoids expiration](https://github.com/actions/upload-artifact#retention-period))
Impact | ★☆☆ *1/3* | Keeps artifacts available, makes CI failures detectable via badge and email
Risk | ★☆☆ *1/3* | Slightly increases …
=> ci: Schedule monthly build to catch regressions

.craftsettings.ini
* Fix Craft Windows build by ignoring Python 2
* GitHub's [Windows Server 2022 images](https://github.com/actions/virtual-environments/issues/4856 ) removed Python 2
* Python 2 build-time [dependency introduced by QtWebEngine](https://github.com/KDE/craft-blueprints-kde/blob/f6674971eaa2607e7bd1d0970dc83e73ad7230f3/libs/qt5/qtwebengine/qtwebengine.py#L43 )
* We rely on KDE's prebuilt QtWebEngine image, so Python 2 is not needed
* Caught by [the monthly scheduled CI build](https://github.com/quassel/quassel/commit/c51ac776a9b4b9fbc3ff9b0063f44acd566732ea ) before it impacted contributors 🎉
*Many thanks to @TheOneRing on `Libera Chat`/`#quassel` for guiding me!*
Impact | ★★★ *3/3* | Fixes Windows builds, makes Windows CI artifacts …
=> ci: Fix Craft Windows build by ignoring Python 2

.craftsettings.ini
* Fix Craft Windows build by ignoring Python 2
* GitHub's [Windows Server 2022 images](https://github.com/actions/virtual-environments/issues/4856 ) removed Python 2
* Python 2 build-time [dependency introduced by QtWebEngine](https://github.com/KDE/craft-blueprints-kde/blob/f6674971eaa2607e7bd1d0970dc83e73ad7230f3/libs/qt5/qtwebengine/qtwebengine.py#L43 )
* We rely on KDE's prebuilt QtWebEngine image, so Python 2 is not needed
* Caught by [the monthly scheduled CI build](https://github.com/quassel/quassel/commit/c51ac776a9b4b9fbc3ff9b0063f44acd566732ea ) before it impacted contributors 🎉
*Many thanks to @TheOneRing on `Libera Chat`/`#quassel` for guiding me!*
Impact | ★★★ *3/3* | Fixes Windows builds, makes Windows CI artifacts …
=> [backport 0.14] ci: Fix Craft Windows build by ignoring Python 2

.github/workflows/main.yml
* Update Xcode version in CI to fix build
* Xcode 12.4 is no longer available
* As of 2022-11-14, [Qt 5 supports up to Xcode 13.x](https://doc.qt.io/qt-5/macos.html )
* [Matches a similar Xcode version bump made last year](https://github.com/quassel/quassel/pull/590 ), now [with semantic versioning](https://github.com/maxim-lobanov/setup-xcode#readme )!
Impact | ★★☆ *2/3* | Fixes automated macOS builds
Risk | ★☆☆ *1/3* | Updated Xcode version may introduce unexpected changes
*As this is a minor change, I've skipped the usual breakdown analysis.  I don't have a Mac to test with.*
=> ci: [mac] Update Qt 5 supported Xcode to v13.x

.github/workflows/main.yml
* Update Xcode version in CI to fix build
* Xcode 12.4 is no longer available
* As of 2022-11-14, [Qt 5 supports up to Xcode 13.x](https://doc.qt.io/qt-5/macos.html )
* [Matches a similar Xcode version bump made last year](https://github.com/quassel/quassel/pull/590 ), now [with semantic versioning](https://github.com/maxim-lobanov/setup-xcode#readme )!
Impact | ★★☆ *2/3* | Fixes automated macOS builds
Risk | ★☆☆ *1/3* | Updated Xcode version may introduce unexpected changes
*As this is a minor change, I've skipped the usual breakdown analysis.  I don't have a Mac to test with.*
=> [backport 0.14] ci: [mac] Update Qt 5 supported Xcode to v13.x

src/uisupport/aboutdata.cpp
When building for KDE (cmake -DUSE_KDE=1), the KAboutData constructor as invoked by uisupport causes the resulting application name to be "org.kde.quassel".
At least on GNOME, this "org.kde.quassel" doesn't match the corresponding "quasselclient.desktop" file, which means the app doesn't get a pretty name/icon in the app launcher, which looks pretty ugly:
The solution is to call [KAboutData::setDesktopFileName()](https://api.kde.org/frameworks/kcoreaddons/html/classKAboutData.html) with the desired name. This means the corresponding .desktop is matched, and you get a pretty name/icon:
This issue doesn't occur when building with USE_KDE=0 for two reasons:
1. Because QtUiApplication already calls QGuiApplication::setDesktopFileName() with the correct value (which is, unfortunately, ignored …
=> uisupport: fix application name for .desktop shell integration

cmake/QuasselCompileSettings.cmake, cmake/QuasselMacros.cmake
Updated the compile settings to detect if the build is occurring on an Apple Silicon based Mac and setting the architecture appropriately.
=> Enable building on M1 (Apple Silicon) Macs

.craftsettings.ini, .github/workflows/main.yml, CMakeLists.txt, cmake/QuasselMacros.cmake, src/client/coreaccountmodel.cpp
The CI configuration has not been touched for a couple of years, and has recently stopped working. Update the list of distros, modernize some things, support both x86_64 and arm64 for macOS, and make the (still broken) Windows build temporarily optional.
=> Fix and modernize CI

src/core/CMakeLists.txt, src/core/backgroundtaskhandler.cpp, src/core/backgroundtaskhandler.h, src/core/corebuffersyncer.cpp, src/core/corebuffersyncer.h, src/core/coresession.cpp, src/core/coresession.h
* Adds a background task handler object to each core session
* Moves buffer deletion to that handler
| - | - | - |
| Impact | ★☆☆  _1/3_ | Prevents the core from timing out while deleting a large buffer |
| Risk | ★★☆  _2/3_ | Only changes buffer deletion, which is not critical functionality |
Currently, while deleting buffers, the core may hang and the IRC connection can time out. With the end of freenode this has become a more pressing matter recently. This PR moves deletion of buffers to a thread per-user to prevent users causing a DoS while simultaneously preventing the core from hanging.
=> [PR-582] Move buffer deletion to a background task

src/common/network.cpp
- Update internal `support` (or `ISUPPORT`) tokens for a network when they change.
| Criteria           | Rank         | Reason                                                                                                                 |
| ----------------- | -------------- | --------------------------------------------------------------------------------------------------------- |
| Impact            | ★☆☆ 1/3 | Keeps the core and client up-to-date with the necessary network configuration. |
| Risk                | ★★☆ 2/3 | May lead to unintended weirdness in handling of some changed tokens.            |
| Intrusiveness | ★☆☆ 1/3  | One line change; doesn't appear to interfere with other PRs.                              |
Currently, if a network changes their configuration in such …
=> Allow updating an ISUPPORT token.

src/client/execwrapper.cpp
The clients execwrapper was using the scriptName instead of the full path fileName to execute scripts leading to scripts only being found and executed if the script directory was also in $PATH or a executable with the same name as the script was in $PATH.
This could also lead to confusion as it executes whatever is in $PATH instead of the actual script in quassels directories.
=> fix client execwrapper not using full path to script

src/core/cipher.cpp, src/core/cipher.h, src/core/coresessioneventprocessor.cpp, src/core/coreuserinputhandler.cpp, src/qtui/topicwidget.cpp
Hello,
this fixes a bunch of crap in the crypto key exchange department. I tested it using other clients (mirccryption), irssi (falsovski irssi-fish) with the monolithic build.
basically fixes https://bugs.quassel-irc.org/issues/1857
simultaneously fixes a rare bug i encountered:   when channel and topic were set with a different key. decryption of topic will then lead to random garbage bytes. Some which will still trigger the stack overflow despite the previous fixes.
also seems to cover integrates/resolve these features pull reqs:
mcps * cbc trigger decryption: https://github.com/quassel/quassel/pull/620
crash on broken topic: https://github.com/quassel/quassel/pull/612
best regards
=> Broken key exchange fix (Compatability with other clients)

src/uisupport/multilineedit.cpp, src/uisupport/multilineedit.h
Quassel crashed on quit in ~MultiLineEdit() with Sonnet >= v5.102 since https://invent.kde.org/frameworks/sonnet/-/commit/ab31a3e27482539985c666a85aa0b07ac52c5c5f
Thread 1 "quasselclient" received signal SIGSEGV, Segmentation fault. Stacktrace:
QObject::removeEventFilter(QObject*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 Sonnet::SpellCheckDecorator::~SpellCheckDecorator() () at /usr/lib/x86_64-linux-gnu/libKF5SonnetUi.so.5 Sonnet::SpellCheckDecorator::~SpellCheckDecorator() () at /usr/lib/x86_64-linux-gnu/libKF5SonnetUi.so.5 QObjectPrivate::deleteChildren() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 QWidget::~QWidget() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 MultiLineEdit::~MultiLineEdit() (this=0x555555f71550, __in_chrg=<optimized out>) at …
=> Fix crash in ~MultiLineEdit() on quit

data/scripts/mpris
- Update documentation
- Allow for `.` in the name of the player name
- Strip `xesam:` from the result
=> data/scripts/mpris: update to use current MPRIS D-Bus interface

src/client/clientauthhandler.cpp, src/client/clientauthhandler.h, src/common/quassel.cpp, src/core/sslserver.cpp
This PR adds client-side support for implicit TLS connections. It's intentionally very minimal, no large refactors, in order to make merging and feedback easier.
This is intended to work with proxies that terminate TLS before the application. From the operational side it significantly simplifies certificate management. Implicit TLS connections also reduce potential privacy leaks and prevent any potential (downgrade) attacks during Quassel protocol negotiation.
In terms of future improvements, I am thinking about implementing the Proxy Protocol (v2) for accurate logging. I would also like to enforce TLSv1.3 minimum on implicit TLS connections, if there are no objections. In general it would be nice to switch to "TLS" as the term used in user-facing strings and also code, instead of "SSL" …
=> Added client-side support for implicit TLS connections
